package com.orellano.biblia360.daoSQLite.sql.spa;

public final class LoadNehemias {
  public LoadNehemias() {}
  public static final String SQL_PARTE_1 = 
    "INSERT INTO Versiculo (\n" +
    "    codLengua_vscl, codVersion_vscl, codLibro_vscl, codCapitulo_vscl, codVersiculo_vscl, encabezado_vscl,\n" +
    "    contenido_vscl,\n" +
    "    parrafo_vscl, codLengua_vscl_ltr, codVersion_vscl_ltr, codLectura_vscl_ltr)\n" +
    "VALUES\n" +
    "('spa', 'RVR1960', 'Neh', 1, 1, 'Oración de Nehemías sobre Jerusalén', 'Palabras de Nehemías hijo de Hacalías. Aconteció en el mes de Quisleu, en el año veinte, estando yo en Susa, capital del reino,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 2, NULL, 'que vino Hanani, uno de mis hermanos, con algunos varones de Judá, y les pregunté por los judíos que habían escapado, que habían quedado de la cautividad, y por Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 3, NULL, 'Y me dijeron: El remanente, los que quedaron de la cautividad, allí en la provincia, están en gran mal y afrenta, y el muro de Jerusalén derribado, y sus puertas quemadas a fuego.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 4, NULL, 'Cuando oí estas palabras me senté y lloré, e hice duelo por algunos días, y ayuné y oré delante del Dios de los cielos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 5, NULL, 'Y dije: Te ruego, oh Jehová, Dios de los cielos, fuerte, grande y temible, que guarda el pacto y la misericordia a los que le aman y guardan sus mandamientos;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 6, NULL, 'esté ahora atento tu oído y abiertos tus ojos para oír la oración de tu siervo, que hago ahora delante de ti día y noche, por los hijos de Israel tus siervos; y confieso los pecados de los hijos de Israel que hemos cometido contra ti; sí, yo y la casa de mi padre hemos pecado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 7, NULL, 'En extremo nos hemos corrompido contra ti, y no hemos guardado los mandamientos, estatutos y preceptos que diste a Moisés tu siervo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 8, NULL, 'Acuérdate ahora de la palabra que diste a Moisés tu siervo, diciendo: Si vosotros pecareis, yo os dispersaré por los pueblos;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 9, NULL, 'pero si os volviereis a mí, y guardareis mis mandamientos, y los pusiereis por obra, aunque vuestra dispersión fuere hasta el extremo de los cielos, de allí os recogeré, y os traeré al lugar que escogí para hacer habitar allí mi nombre.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 10, NULL, 'Ellos, pues, son tus siervos y tu pueblo, los cuales redimiste con tu gran poder, y con tu mano poderosa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 1, 11, NULL, 'Te ruego, oh Jehová, esté ahora atento tu oído a la oración de tu siervo, y a la oración de tus siervos, quienes desean reverenciar tu nombre; concede ahora buen éxito a tu siervo, y dale gracia delante de aquel varón. Porque yo servía de copero al rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 1, 'Artajerjes envía a Nehemías a Jerusalén', 'Sucedió en el mes de Nisán, en el año veinte del rey Artajerjes, que estando ya el vino delante de él, tomé el vino y lo serví al rey. Y como yo no había estado antes triste en su presencia,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 2, NULL, 'me dijo el rey: ¿Por qué está triste tu rostro? pues no estás enfermo. No es esto sino quebranto de corazón. Entonces temí en gran manera.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 3, NULL, 'Y dije al rey: Para siempre viva el rey. ¿Cómo no estará triste mi rostro, cuando la ciudad, casa de los sepulcros de mis padres, está desierta, y sus puertas consumidas por el fuego?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 4, NULL, 'Me dijo el rey: ¿Qué cosa pides? Entonces oré al Dios de los cielos,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 5, NULL, 'y dije al rey: Si le place al rey, y tu siervo ha hallado gracia delante de ti, envíame a Judá, a la ciudad de los sepulcros de mis padres, y la reedificaré.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 6, NULL, 'Entonces el rey me dijo (y la reina estaba sentada junto a él): ¿Cuánto durará tu viaje, y cuándo volverás? Y agradó al rey enviarme, después que yo le señalé tiempo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 7, NULL, 'Además dije al rey: Si le place al rey, que se me den cartas para los gobernadores al otro lado del río, para que me franqueen el paso hasta que llegue a Judá;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 8, NULL, 'y carta para Asaf guarda del bosque del rey, para que me dé madera para enmaderar las puertas del palacio de la casa, y para el muro de la ciudad, y la casa en que yo estaré. Y me lo concedió el rey, según la benéfica mano de mi Dios sobre mí.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 9, NULL, 'Vine luego a los gobernadores del otro lado del río, y les di las cartas del rey. Y el rey envió conmigo capitanes del ejército y gente de a caballo.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 10, NULL, 'Pero oyéndolo Sanbalat horonita y Tobías el siervo amonita, les disgustó en extremo que viniese alguno para procurar el bien de los hijos de Israel.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 11, 'Nehemías anima al pueblo a reedificar los muros', 'Llegué, pues, a Jerusalén, y después de estar allí tres días,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 12, NULL, 'me levanté de noche, yo y unos pocos varones conmigo, y no declaré a hombre alguno lo que Dios había puesto en mi corazón que hiciese en Jerusalén; ni había cabalgadura conmigo, excepto la única en que yo cabalgaba.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 13, NULL, 'Y salí de noche por la puerta del Valle hacia la fuente del Dragón y a la puerta del Muladar; y observé los muros de Jerusalén que estaban derribados, y sus puertas que estaban consumidas por el fuego.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 14, NULL, 'Pasé luego a la puerta de la Fuente, y al estanque del Rey; pero no había lugar por donde pasase la cabalgadura en que iba.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 15, NULL, 'Y subí de noche por el torrente y observé el muro, y di la vuelta y entré por la puerta del Valle, y me volví.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 16, NULL, 'Y no sabían los oficiales a dónde yo había ido, ni qué había hecho; ni hasta entonces lo había declarado yo a los judíos y sacerdotes, ni a los nobles y oficiales, ni a los demás que hacían la obra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 17, NULL, 'Les dije, pues: Vosotros veis el mal en que estamos, que Jerusalén está desierta, y sus puertas consumidas por el fuego; venid, y edifiquemos el muro de Jerusalén, y no estemos más en oprobio.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 18, NULL, 'Entonces les declaré cómo la mano de mi Dios había sido buena sobre mí, y asimismo las palabras que el rey me había dicho. Y dijeron: Levantémonos y edifiquemos. Así esforzaron sus manos para bien.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 19, NULL, 'Pero cuando lo oyeron Sanbalat horonita, Tobías el siervo amonita, y Gesem el árabe, hicieron escarnio de nosotros, y nos despreciaron, diciendo: ¿Qué es esto que hacéis vosotros? ¿Os rebeláis contra el rey?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 2, 20, NULL, 'Y en respuesta les dije: El Dios de los cielos, él nos prosperará, y nosotros sus siervos nos levantaremos y edificaremos, porque vosotros no tenéis parte ni derecho ni memoria en Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 1, 'Reparto del trabajo de reedificación', 'Entonces se levantó el sumo sacerdote Eliasib con sus hermanos los sacerdotes, y edificaron la puerta de las Ovejas. Ellos arreglaron y levantaron sus puertas hasta la torre de Hamea, y edificaron hasta la torre de Hananeel.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 2, NULL, 'Junto a ella edificaron los varones de Jericó, y luego edificó Zacur hijo de Imri.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 3, NULL, 'Los hijos de Senaa edificaron la puerta del Pescado; ellos la enmaderaron, y levantaron sus puertas, con sus cerraduras y sus cerrojos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 4, NULL, 'Junto a ellos restauró Meremot hijo de Urías, hijo de Cos, y al lado de ellos restauró Mesulam hijo de Berequías, hijo de Mesezabeel. Junto a ellos restauró Sadoc hijo de Baana.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 5, NULL, 'E inmediato a ellos restauraron los tecoítas; pero sus grandes no se prestaron para ayudar a la obra de su Señor.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 6, NULL, 'La puerta Vieja fue restaurada por Joiada hijo de Paseah y Mesulam hijo de Besodías; ellos la enmaderaron, y levantaron sus puertas, con sus cerraduras y cerrojos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 7, NULL, 'Junto a ellos restauró Melatías gabaonita, y Jadón meronotita, varones de Gabaón y de Mizpa, que estaban bajo el dominio del gobernador del otro lado del río.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 8, NULL, 'Junto a ellos restauró Uziel hijo de Harhaía, de los plateros; junto al cual restauró también Hananías, hijo de un perfumero. Así dejaron reparada a Jerusalén hasta el muro ancho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 9, NULL, 'Junto a ellos restauró también Refaías hijo de Hur, gobernador de la mitad de la región de Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 10, NULL, 'Asimismo restauró junto a ellos, y frente a su casa, Jedaías hijo de Harumaf; y junto a él restauró Hatús hijo de Hasabnías.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 11, NULL, 'Malquías hijo de Harim y Hasub hijo de Pahat-moab restauraron otro tramo, y la torre de los Hornos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 12, NULL, 'Junto a ellos restauró Salum hijo de Halohes, gobernador de la mitad de la región de Jerusalén, él con sus hijas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 13, NULL, 'La puerta del Valle la restauró Hanún con los moradores de Zanoa; ellos la reedificaron, y levantaron sus puertas, con sus cerraduras y sus cerrojos, y mil codos del muro, hasta la puerta del Muladar.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 14, NULL, 'Reedificó la puerta del Muladar Malquías hijo de Recab, gobernador de la provincia de Bet-haquerem; él la reedificó, y levantó sus puertas, sus cerraduras y sus cerrojos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 15, NULL, 'Salum hijo de Colhoze, gobernador de la región de Mizpa, restauró la puerta de la Fuente; él la reedificó, la enmaderó y levantó sus puertas, sus cerraduras y sus cerrojos, y el muro del estanque de Siloé hacia el huerto del rey, y hasta las gradas que descienden de la ciudad de David.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 16, NULL, 'Después de él restauró Nehemías hijo de Azbuc, gobernador de la mitad de la región de Bet-sur, hasta delante de los sepulcros de David, y hasta el estanque labrado, y hasta la casa de los Valientes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 17, NULL, 'Tras él restauraron los levitas; Rehum hijo de Bani, y junto a él restauró Hasabías, gobernador de la mitad de la región de Keila, por su región.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 18, NULL, 'Después de él restauraron sus hermanos, Bavai hijo de Henadad, gobernador de la mitad de la región de Keila.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 19, NULL, 'Junto a él restauró Ezer hijo de Jesúa, gobernador de Mizpa, otro tramo frente a la subida de la armería de la esquina.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 20, NULL, 'Después de él Baruc hijo de Zabai con todo fervor restauró otro tramo, desde la esquina hasta la puerta de la casa de Eliasib sumo sacerdote.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 21, NULL, 'Tras él restauró Meremot hijo de Urías hijo de Cos otro tramo, desde la entrada de la casa de Eliasib hasta el extremo de la casa de Eliasib.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 22, NULL, 'Después de él restauraron los sacerdotes, los varones de la llanura.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 23, NULL, 'Después de ellos restauraron Benjamín y Hasub, frente a su casa; y después de estos restauró Azarías hijo de Maasías, hijo de Ananías, cerca de su casa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 24, NULL, 'Después de él restauró Binúi hijo de Henadad otro tramo, desde la casa de Azarías hasta el ángulo entrante del muro, y hasta la esquina.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 25, NULL, 'Palal hijo de Uzai, enfrente de la esquina y la torre alta que sale de la casa del rey, que está en el patio de la cárcel. Después de él, Pedaías hijo de Faros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 26, NULL, 'Y los sirvientes del templo que habitaban en Ofel restauraron hasta enfrente de la puerta de las Aguas al oriente, y la torre que sobresalía.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 27, NULL, 'Después de ellos restauraron los tecoítas otro tramo, enfrente de la gran torre que sobresale, hasta el muro de Ofel.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 28, NULL, 'Desde la puerta de los Caballos restauraron los sacerdotes, cada uno enfrente de su casa.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 29, NULL, 'Después de ellos restauró Sadoc hijo de Imer, enfrente de su casa; y después de él restauró Semaías hijo de Secanías, guarda de la puerta Oriental.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 30, NULL, 'Tras él, Hananías hijo de Selemías y Hanún hijo sexto de Salaf restauraron otro tramo. Después de ellos restauró Mesulam hijo de Berequías, enfrente de su cámara.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 31, NULL, 'Después de él restauró Malquías hijo del platero, hasta la casa de los sirvientes del templo y de los comerciantes, enfrente de la puerta del Juicio, y hasta la sala de la esquina.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 3, 32, NULL, 'Y entre la sala de la esquina y la puerta de las Ovejas, restauraron los plateros y los comerciantes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 1, 'Precauciones contra los enemigos', 'Cuando oyó Sanbalat que nosotros edificábamos el muro, se enojó y se enfureció en gran manera, e hizo escarnio de los judíos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 2, NULL, 'Y habló delante de sus hermanos y del ejército de Samaria, y dijo: ¿Qué hacen estos débiles judíos? ¿Se les permitirá volver a ofrecer sus sacrificios? ¿Acabarán en un día? ¿Resucitarán de los montones del polvo las piedras que fueron quemadas?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 3, NULL, 'Y estaba junto a él Tobías amonita, el cual dijo: Lo que ellos edifican del muro de piedra, si subiere una zorra lo derribará.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 4, NULL, 'Oye, oh Dios nuestro, que somos objeto de su menosprecio, y vuelve el baldón de ellos sobre su cabeza, y entrégalos por despojo en la tierra de su cautiverio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 5, NULL, 'No cubras su iniquidad, ni su pecado sea borrado delante de ti, porque se airaron contra los que edificaban.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 6, NULL, 'Edificamos, pues, el muro, y toda la muralla fue terminada hasta la mitad de su altura, porque el pueblo tuvo ánimo para trabajar.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 7, NULL, 'Pero aconteció que oyendo Sanbalat y Tobías, y los árabes, los amonitas y los de Asdod, que los muros de Jerusalén eran reparados, porque ya los portillos comenzaban a ser cerrados, se encolerizaron mucho;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 8, NULL, 'y conspiraron todos a una para venir a atacar a Jerusalén y hacerle daño.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 9, NULL, 'Entonces oramos a nuestro Dios, y por causa de ellos pusimos guarda contra ellos de día y de noche.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 10, NULL, 'Y dijo Judá: Las fuerzas de los acarreadores se han debilitado, y el escombro es mucho, y no podemos edificar el muro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 11, NULL, 'Y nuestros enemigos dijeron: No sepan, ni vean, hasta que entremos en medio de ellos y los matemos, y hagamos cesar la obra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 12, NULL, 'Pero sucedió que cuando venían los judíos que habitaban entre ellos, nos decían hasta diez veces: De todos los lugares de donde volviereis, ellos caerán sobre vosotros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 13, NULL, 'Entonces por las partes bajas del lugar, detrás del muro, y en los sitios abiertos, puse al pueblo por familias, con sus espadas, con sus lanzas y con sus arcos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 14, NULL, 'Después miré, y me levanté y dije a los nobles y a los oficiales, y al resto del pueblo: No temáis delante de ellos; acordaos del Señor, grande y temible, y pelead por vuestros hermanos, por vuestros hijos y por vuestras hijas, por vuestras mujeres y por vuestras casas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 15, NULL, 'Y cuando oyeron nuestros enemigos que lo habíamos entendido, y que Dios había desbaratado el consejo de ellos, nos volvimos todos al muro, cada uno a su tarea.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 16, NULL, 'Desde aquel día la mitad de mis siervos trabajaba en la obra, y la otra mitad tenía lanzas, escudos, arcos y corazas; y detrás de ellos estaban los jefes de toda la casa de Judá.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 17, NULL, 'Los que edificaban en el muro, los que acarreaban, y los que cargaban, con una mano trabajaban en la obra, y en la otra tenían la espada.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 18, NULL, 'Porque los que edificaban, cada uno tenía su espada ceñida a sus lomos, y así edificaban; y el que tocaba la trompeta estaba junto a mí.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 19, NULL, 'Y dije a los nobles, y a los oficiales y al resto del pueblo: La obra es grande y extensa, y nosotros estamos apartados en el muro, lejos unos de otros.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 20, NULL, 'En el lugar donde oyereis el sonido de la trompeta, reuníos allí con nosotros; nuestro Dios peleará por nosotros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 21, NULL, 'Nosotros, pues, trabajábamos en la obra; y la mitad de ellos tenían lanzas desde la subida del alba hasta que salían las estrellas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 22, NULL, 'También dije entonces al pueblo: Cada uno con su criado permanezca dentro de Jerusalén, y de noche sirvan de centinela y de día en la obra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 4, 23, NULL, 'Y ni yo ni mis hermanos, ni mis jóvenes, ni la gente de guardia que me seguía, nos quitamos nuestro vestido; cada uno se desnudaba solamente para bañarse.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 1, 'Abolición de la usura', 'Entonces hubo gran clamor del pueblo y de sus mujeres contra sus hermanos judíos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 2, NULL, 'Había quien decía: Nosotros, nuestros hijos y nuestras hijas, somos muchos; por tanto, hemos pedido prestado grano para comer y vivir.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 3, NULL, 'Y había quienes decían: Hemos empeñado nuestras tierras, nuestras viñas y nuestras casas, para comprar grano, a causa del hambre.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 4, NULL, 'Y había quienes decían: Hemos tomado prestado dinero para el tributo del rey, sobre nuestras tierras y viñas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 5, NULL, 'Ahora bien, nuestra carne es como la carne de nuestros hermanos, nuestros hijos como sus hijos; y he aquí que nosotros dimos nuestros hijos y nuestras hijas a servidumbre, y algunas de nuestras hijas lo están ya, y no tenemos posibilidad de rescatarlas, porque nuestras tierras y nuestras viñas son de otros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 6, NULL, 'Y me enojé en gran manera cuando oí su clamor y estas palabras.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 7, NULL, 'Entonces lo medité, y reprendí a los nobles y a los oficiales, y les dije: ¿Exigís interés cada uno a vuestros hermanos? Y convoqué contra ellos una gran asamblea,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 8, NULL, 'y les dije: Nosotros según nuestras posibilidades rescatamos a nuestros hermanos judíos que habían sido vendidos a las naciones; ¿y vosotros vendéis aun a vuestros hermanos, y serán vendidos a nosotros? Y callaron, pues no tuvieron qué responder.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 9, NULL, 'Y dije: No es bueno lo que hacéis. ¿No andaréis en el temor de nuestro Dios, para no ser oprobio de las naciones enemigas nuestras?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 10, NULL, 'También yo y mis hermanos y mis criados les hemos prestado dinero y grano; quitémosles ahora este gravamen.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 11, NULL, 'Os ruego que les devolváis hoy sus tierras, sus viñas, sus olivares y sus casas, y la centésima parte del dinero, del grano, del vino y del aceite, que demandáis de ellos como interés.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 12, NULL, 'Y dijeron: Lo devolveremos, y nada les demandaremos; haremos así como tú dices. Entonces convoqué a los sacerdotes, y les hice jurar que harían conforme a esto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 13, NULL, 'Además sacudí mi vestido, y dije: Así sacuda Dios de su casa y de su trabajo a todo hombre que no cumpliere esto, y así sea sacudido y vacío. Y respondió toda la congregación: ¡Amén! y alabaron a Jehová. Y el pueblo hizo conforme a esto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 14, NULL, 'También desde el día que me mandó el rey que fuese gobernador de ellos en la tierra de Judá, desde el año veinte del rey Artajerjes hasta el año treinta y dos, doce años, ni yo ni mis hermanos comimos el pan del gobernador.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 15, NULL, 'Pero los primeros gobernadores que fueron antes de mí abrumaron al pueblo, y tomaron de ellos por el pan y por el vino más de cuarenta siclos de plata, y aun sus criados se enseñoreaban del pueblo; pero yo no hice así, a causa del temor de Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 16, NULL, 'También en la obra de este muro restauré mi parte, y no compramos heredad; y todos mis criados juntos estaban allí en la obra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 17, NULL, 'Además, ciento cincuenta judíos y oficiales, y los que venían de las naciones que había alrededor de nosotros, estaban a mi mesa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 18, NULL, 'Y lo que se preparaba para cada día era un buey y seis ovejas escogidas; también eran preparadas para mí aves, y cada diez días vino en toda abundancia; y con todo esto nunca requerí el pan del gobernador, porque la servidumbre de este pueblo era grave.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 5, 19, NULL, 'Acuérdate de mí para bien, Dios mío, y de todo lo que hice por este pueblo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 1, 'Maquinaciones de los adversarios', 'Cuando oyeron Sanbalat y Tobías y Gesem el árabe, y los demás de nuestros enemigos, que yo había edificado el muro, y que no quedaba en él portillo (aunque hasta aquel tiempo no había puesto las hojas en las puertas),', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 2, NULL, 'Sanbalat y Gesem enviaron a decirme: Ven y reunámonos en alguna de las aldeas en el campo de Ono. Mas ellos habían pensado hacerme mal.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 3, NULL, 'Y les envié mensajeros, diciendo: Yo hago una gran obra, y no puedo ir; porque cesaría la obra, dejándola yo para ir a vosotros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 4, NULL, 'Y enviaron a mí con el mismo asunto hasta cuatro veces, y yo les respondí de la misma manera.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 5, NULL, 'Entonces Sanbalat envió a mí su criado para decir lo mismo por quinta vez, con una carta abierta en su mano,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 6, NULL, 'en la cual estaba escrito: Se ha oído entre las naciones, y Gasmu lo dice, que tú y los judíos pensáis rebelaros; y que por eso edificas tú el muro, con la mira, según estas palabras, de ser tú su rey;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 7, NULL, 'y que has puesto profetas que proclamen acerca de ti en Jerusalén, diciendo: ¡Hay rey en Judá! Y ahora serán oídas del rey las tales palabras; ven, por tanto, y consultemos juntos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 8, NULL, 'Entonces envié yo a decirle: No hay tal cosa como dices, sino que de tu corazón tú lo inventas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 9, NULL, 'Porque todos ellos nos amedrentaban, diciendo: Se debilitarán las manos de ellos en la obra, y no será terminada. Ahora, pues, oh Dios, fortalece tú mis manos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 10, NULL, 'Vine luego a casa de Semaías hijo de Delaía, hijo de Mehetabel, porque él estaba encerrado; el cual me dijo: Reunámonos en la casa de Dios, dentro del templo, y cerremos las puertas del templo, porque vienen para matarte; sí, esta noche vendrán a matarte.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 11, NULL, 'Entonces dije: ¿Un hombre como yo ha de huir? ¿Y quién, que fuera como yo, entraría al templo para salvarse la vida? No entraré.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 12, NULL, 'Y entendí que Dios no lo había enviado, sino que hablaba aquella profecía contra mí porque Tobías y Sanbalat lo habían sobornado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 13, NULL, 'Porque fue sobornado para hacerme temer así, y que pecase, y les sirviera de mal nombre con que fuera yo infamado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 14, NULL, 'Acuérdate, Dios mío, de Tobías y de Sanbalat, conforme a estas cosas que hicieron; también acuérdate de Noadías profetisa, y de los otros profetas que procuraban infundirme miedo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 15, NULL, 'Fue terminado, pues, el muro, el veinticinco del mes de Elul, en cincuenta y dos días.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 16, NULL, 'Y cuando lo oyeron todos nuestros enemigos, temieron todas las naciones que estaban alrededor de nosotros, y se sintieron humillados, y conocieron que por nuestro Dios había sido hecha esta obra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 17, NULL, 'Asimismo en aquellos días iban muchas cartas de los principales de Judá a Tobías, y las de Tobías venían a ellos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 18, NULL, 'Porque muchos en Judá se habían conjurado con él, porque era yerno de Secanías hijo de Ara; y Johanán su hijo había tomado por mujer a la hija de Mesulam hijo de Berequías.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 6, 19, NULL, 'También contaban delante de mí las buenas obras de él, y a él le referían mis palabras. Y enviaba Tobías cartas para atemorizarme.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 1, 'Nehemías designa dirigentes', 'Luego que el muro fue edificado, y colocadas las puertas, y fueron señalados porteros y cantores y levitas,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 2, NULL, 'mandé a mi hermano Hanani, y a Hananías, jefe de la fortaleza de Jerusalén (porque este era varón de verdad y temeroso de Dios, más que muchos);', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 3, NULL, 'y les dije: No se abran las puertas de Jerusalén hasta que caliente el sol; y aunque haya gente allí, cerrad las puertas y atrancadlas. Y señalé guardas de los moradores de Jerusalén, cada cual en su turno, y cada uno delante de su casa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 4, NULL, 'Porque la ciudad era espaciosa y grande, pero poco pueblo dentro de ella, y no había casas reedificadas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 5, 'Los que volvieron con Zorobabel', 'Entonces puso Dios en mi corazón que reuniese a los nobles y oficiales y al pueblo, para que fuesen empadronados según sus genealogías. Y hallé el libro de la genealogía de los que habían subido antes, y encontré en él escrito así:', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 6, NULL, 'Estos son los hijos de la provincia que subieron del cautiverio, de los que llevó cautivos Nabucodonosor rey de Babilonia, y que volvieron a Jerusalén y a Judá, cada uno a su ciudad,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 7, NULL, 'los cuales vinieron con Zorobabel, Jesúa, Nehemías, Azarías, Raamías, Nahamani, Mardoqueo, Bilsán, Misperet, Bigvai, Nehum y Baana. El número de los varones del pueblo de Israel:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 8, NULL, 'Los hijos de Paros, dos mil ciento setenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 9, NULL, 'Los hijos de Sefatías, trescientos setenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 10, NULL, 'Los hijos de Ara, seiscientos cincuenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 11, NULL, 'Los hijos de Pahat-moab, de los hijos de Jesúa y de Joab, dos mil ochocientos dieciocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 12, NULL, 'Los hijos de Elam, mil doscientos cincuenta y cuatro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 13, NULL, 'Los hijos de Zatu, ochocientos cuarenta y cinco.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 14, NULL, 'Los hijos de Zacai, setecientos sesenta.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 15, NULL, 'Los hijos de Binúi, seiscientos cuarenta y ocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 16, NULL, 'Los hijos de Bebai, seiscientos veintiocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 17, NULL, 'Los hijos de Azgad, dos mil seiscientos veintidós.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 18, NULL, 'Los hijos de Adonicam, seiscientos sesenta y siete.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 19, NULL, 'Los hijos de Bigvai, dos mil sesenta y siete.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 20, NULL, 'Los hijos de Adín, seiscientos cincuenta y cinco.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 21, NULL, 'Los hijos de Ater, de Ezequías, noventa y ocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 22, NULL, 'Los hijos de Hasum, trescientos veintiocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 23, NULL, 'Los hijos de Bezai, trescientos veinticuatro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 24, NULL, 'Los hijos de Harif, ciento doce.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 25, NULL, 'Los hijos de Gabaón, noventa y cinco.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 26, NULL, 'Los varones de Belén y de Netofa, ciento ochenta y ocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 27, NULL, 'Los varones de Anatot, ciento veintiocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 28, NULL, 'Los varones de Bet-azmavet, cuarenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 29, NULL, 'Los varones de Quiriat-jearim, Cafira y Beerot, setecientos cuarenta y tres.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 30, NULL, 'Los varones de Ramá y de Geba, seiscientos veintiuno.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 31, NULL, 'Los varones de Micmas, ciento veintidós.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 32, NULL, 'Los varones de Bet-el y de Hai, ciento veintitrés.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 33, NULL, 'Los varones del otro Nebo, cincuenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 34, NULL, 'Los hijos del otro Elam, mil doscientos cincuenta y cuatro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 35, NULL, 'Los hijos de Harim, trescientos veinte.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 36, NULL, 'Los hijos de Jericó, trescientos cuarenta y cinco.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 37, NULL, 'Los hijos de Lod, Hadid y Ono, setecientos veintiuno.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 38, NULL, 'Los hijos de Senaa, tres mil novecientos treinta.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 39, NULL, 'Sacerdotes: los hijos de Jedaías, de la casa de Jesúa, novecientos setenta y tres.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 40, NULL, 'Los hijos de Imer, mil cincuenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 41, NULL, 'Los hijos de Pasur, mil doscientos cuarenta y siete.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 42, NULL, 'Los hijos de Harim, mil diecisiete.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 43, NULL, 'Levitas: los hijos de Jesúa, de Cadmiel, de los hijos de Hodavías, setenta y cuatro.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 44, NULL, 'Cantores: los hijos de Asaf, ciento cuarenta y ocho.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 45, NULL, 'Porteros: Los hijos de Salum, los hijos de Ater, los hijos de Talmón, los hijos de Acub, los hijos de Hatita y los hijos de Sobai, ciento treinta y ocho.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 46, NULL, 'Sirvientes del templo: los hijos de Ziha, los hijos de Hasufa, los hijos de Tabaot,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 47, NULL, 'los hijos de Queros, los hijos de Siaha, los hijos de Padón,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 48, NULL, 'los hijos de Lebana, los hijos de Hagaba, los hijos de Salmai,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 49, NULL, 'los hijos de Hanán, los hijos de Gidel, los hijos de Gahar,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 50, NULL, 'los hijos de Reaía, los hijos de Rezín, los hijos de Necoda,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 51, NULL, 'los hijos de Gazam, los hijos de Uza, los hijos de Paseah,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 52, NULL, 'los hijos de Besai, los hijos de Mehunim, los hijos de Nefisesim,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 53, NULL, 'los hijos de Bacbuc, los hijos de Hacufa, los hijos de Harhur,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 54, NULL, 'los hijos de Bazlut, los hijos de Mehída, los hijos de Harsa,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 55, NULL, 'los hijos de Barcos, los hijos de Sísara, los hijos de Tema,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 56, NULL, 'los hijos de Nezía, y los hijos de Hatifa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 57, NULL, 'Los hijos de los siervos de Salomón: los hijos de Sotai, los hijos de Soferet, los hijos de Perida,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 58, NULL, 'los hijos de Jaala, los hijos de Darcón, los hijos de Gidel,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 59, NULL, 'los hijos de Sefatías, los hijos de Hatil, los hijos de Poqueret-hazebaim, los hijos de Amón.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 60, NULL, 'Todos los sirvientes del templo e hijos de los siervos de Salomón, trescientos noventa y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 61, NULL, 'Y estos son los que subieron de Tel-mela, Tel-harsa, Querub, Adón e Imer, los cuales no pudieron mostrar la casa de sus padres, ni su genealogía, si eran de Israel:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 62, NULL, 'los hijos de Delaía, los hijos de Tobías y los hijos de Necoda, seiscientos cuarenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 63, NULL, 'Y de los sacerdotes: los hijos de Habaía, los hijos de Cos y los hijos de Barzilai, el cual tomó mujer de las hijas de Barzilai galaadita, y se llamó del nombre de ellas.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 64, NULL, 'Estos buscaron su registro de genealogías, y no se halló; y fueron excluidos del sacerdocio,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 65, NULL, 'y les dijo el gobernador que no comiesen de las cosas más santas, hasta que hubiese sacerdote con Urim y Tumim.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 66, NULL, 'Toda la congregación junta era de cuarenta y dos mil trescientos sesenta,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 67, NULL, 'sin sus siervos y siervas, que eran siete mil trescientos treinta y siete; y entre ellos había doscientos cuarenta y cinco cantores y cantoras.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 68, NULL, 'Sus caballos, setecientos treinta y seis; sus mulos, doscientos cuarenta y cinco;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 69, NULL, 'camellos, cuatrocientos treinta y cinco; asnos, seis mil setecientos veinte.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 70, NULL, 'Y algunos de los cabezas de familias dieron ofrendas para la obra. El gobernador dio para el tesoro mil dracmas de oro, cincuenta tazones, y quinientas treinta vestiduras sacerdotales.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 71, NULL, 'Los cabezas de familias dieron para el tesoro de la obra veinte mil dracmas de oro y dos mil doscientas libras de plata.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 72, NULL, 'Y el resto del pueblo dio veinte mil dracmas de oro, dos mil libras de plata, y sesenta y siete vestiduras sacerdotales.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 7, 73, NULL, 'Y habitaron los sacerdotes, los levitas, los porteros, los cantores, los del pueblo, los sirvientes del templo y todo Israel, en sus ciudades. Venido el mes séptimo, los hijos de Israel estaban en sus ciudades;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 1, NULL, '1 y se juntó todo el pueblo como un solo hombre en la plaza que está delante de la puerta de las Aguas, y dijeron a Esdras el escriba que trajese el libro de la ley de Moisés, la cual Jehová había dado a Israel.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 2, NULL, 'Y el sacerdote Esdras trajo la ley delante de la congregación, así de hombres como de mujeres y de todos los que podían entender, el primer día del mes séptimo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 3, NULL, 'Y leyó en el libro delante de la plaza que está delante de la puerta de las Aguas, desde el alba hasta el mediodía, en presencia de hombres y mujeres y de todos los que podían entender; y los oídos de todo el pueblo estaban atentos al libro de la ley.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 4, NULL, 'Y el escriba Esdras estaba sobre un púlpito de madera que habían hecho para ello, y junto a él estaban Matatías, Sema, Anías, Urías, Hilcías y Maasías a su mano derecha; y a su mano izquierda, Pedaías, Misael, Malquías, Hasum, Hasbadana, Zacarías y Mesulam.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 5, NULL, 'Abrió, pues, Esdras el libro a ojos de todo el pueblo, porque estaba más alto que todo el pueblo; y cuando lo abrió, todo el pueblo estuvo atento.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 6, NULL, 'Bendijo entonces Esdras a Jehová, Dios grande. Y todo el pueblo respondió: ¡Amén! ¡Amén! alzando sus manos; y se humillaron y adoraron a Jehová inclinados a tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 7, NULL, 'Y los levitas Jesúa, Bani, Serebías, Jamín, Acub, Sabetai, Hodías, Maasías, Kelita, Azarías, Jozabed, Hanán y Pelaía, hacían entender al pueblo la ley; y el pueblo estaba atento en su lugar.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 8, NULL, 'Y leían en el libro de la ley de Dios claramente, y ponían el sentido, de modo que entendiesen la lectura.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 9, NULL, 'Y Nehemías el gobernador, y el sacerdote Esdras, escriba, y los levitas que hacían entender al pueblo, dijeron a todo el pueblo: Día santo es a Jehová nuestro Dios; no os entristezcáis, ni lloréis; porque todo el pueblo lloraba oyendo las palabras de la ley.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 10, NULL, 'Luego les dijo: Id, comed grosuras, y bebed vino dulce, y enviad porciones a los que no tienen nada preparado; porque día santo es a nuestro Señor; no os entristezcáis, porque el gozo de Jehová es vuestra fuerza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 11, NULL, 'Los levitas, pues, hacían callar a todo el pueblo, diciendo: Callad, porque es día santo, y no os entristezcáis.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 12, NULL, 'Y todo el pueblo se fue a comer y a beber, y a obsequiar porciones, y a gozar de grande alegría, porque habían entendido las palabras que les habían enseñado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 13, NULL, 'Al día siguiente se reunieron los cabezas de las familias de todo el pueblo, sacerdotes y levitas, a Esdras el escriba, para entender las palabras de la ley.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 14, NULL, 'Y hallaron escrito en la ley que Jehová había mandado por mano de Moisés, que habitasen los hijos de Israel en tabernáculos en la fiesta solemne del mes séptimo;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 15, NULL, 'y que hiciesen saber, y pasar pregón por todas sus ciudades y por Jerusalén, diciendo: Salid al monte, y traed ramas de olivo, de olivo silvestre, de arrayán, de palmeras y de todo árbol frondoso, para hacer tabernáculos, como está escrito.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 16, NULL, 'Salió, pues, el pueblo, y trajeron ramas e hicieron tabernáculos, cada uno sobre su terrado, en sus patios, en los patios de la casa de Dios, en la plaza de la puerta de las Aguas, y en la plaza de la puerta de Efraín.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 17, NULL, 'Y toda la congregación que volvió de la cautividad hizo tabernáculos, y en tabernáculos habitó; porque desde los días de Josué hijo de Nun hasta aquel día, no habían hecho así los hijos de Israel. Y hubo alegría muy grande.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 8, 18, NULL, 'Y leyó Esdras en el libro de la ley de Dios cada día, desde el primer día hasta el último; e hicieron la fiesta solemne por siete días, y el octavo día fue de solemne asamblea, según el rito.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 1, 'Esdras confiesa los pecados de Israel', 'El día veinticuatro del mismo mes se reunieron los hijos de Israel en ayuno, y con cilicio y tierra sobre sí.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 2, NULL, 'Y ya se había apartado la descendencia de Israel de todos los extranjeros; y estando en pie, confesaron sus pecados, y las iniquidades de sus padres.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 3, NULL, 'Y puestos de pie en su lugar, leyeron el libro de la ley de Jehová su Dios la cuarta parte del día, y la cuarta parte confesaron sus pecados y adoraron a Jehová su Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 4, NULL, 'Luego se levantaron sobre la grada de los levitas, Jesúa, Bani, Cadmiel, Sebanías, Buni, Serebías, Bani y Quenani, y clamaron en voz alta a Jehová su Dios.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 5, NULL, 'Y dijeron los levitas Jesúa, Cadmiel, Bani, Hasabnías, Serebías, Hodías, Sebanías y Petaías: Levantaos, bendecid a Jehová vuestro Dios desde la eternidad hasta la eternidad; y bendígase el nombre tuyo, glorioso y alto sobre toda bendición y alabanza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 6, NULL, 'Tú solo eres Jehová; tú hiciste los cielos, y los cielos de los cielos, con todo su ejército, la tierra y todo lo que está en ella, los mares y todo lo que hay en ellos; y tú vivificas todas estas cosas, y los ejércitos de los cielos te adoran.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 7, NULL, 'Tú eres, oh Jehová, el Dios que escogiste a Abram, y lo sacaste de Ur de los caldeos, y le pusiste el nombre Abraham;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 8, NULL, 'y hallaste fiel su corazón delante de ti, e hiciste pacto con él para darle la tierra del cananeo, del heteo, del amorreo, del ferezeo, del jebuseo y del gergeseo, para darla a su descendencia; y cumpliste tu palabra, porque eres justo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 9, NULL, 'Y miraste la aflicción de nuestros padres en Egipto, y oíste el clamor de ellos en el Mar Rojo;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 10, NULL, 'e hiciste señales y maravillas contra Faraón, contra todos sus siervos, y contra todo el pueblo de su tierra, porque sabías que habían procedido con soberbia contra ellos; y te hiciste nombre grande, como en este día.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 11, NULL, 'Dividiste el mar delante de ellos, y pasaron por medio de él en seco; y a sus perseguidores echaste en las profundidades, como una piedra en profundas aguas.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 12, NULL, 'Con columna de nube los guiaste de día, y con columna de fuego de noche, para alumbrarles el camino por donde habían de ir.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 13, NULL, 'Y sobre el monte de Sinaí descendiste, y hablaste con ellos desde el cielo, y les diste juicios rectos, leyes verdaderas, y estatutos y mandamientos buenos,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 14, NULL, 'y les ordenaste el día de reposo santo para ti, y por mano de Moisés tu siervo les prescribiste mandamientos, estatutos y la ley.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 15, NULL, 'Les diste pan del cielo en su hambre, y en su sed les sacaste aguas de la peña; y les dijiste que entrasen a poseer la tierra, por la cual alzaste tu mano y juraste que se la darías.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 16, NULL, 'Mas ellos y nuestros padres fueron soberbios, y endurecieron su cerviz, y no escucharon tus mandamientos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 17, NULL, 'No quisieron oír, ni se acordaron de tus maravillas que habías hecho con ellos; antes endurecieron su cerviz, y en su rebelión pensaron poner caudillo para volverse a su servidumbre. Pero tú eres Dios que perdonas, clemente y piadoso, tardo para la ira, y grande en misericordia, porque no los abandonaste.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 18, NULL, 'Además, cuando hicieron para sí becerro de fundición y dijeron: Este es tu Dios que te hizo subir de Egipto; y cometieron grandes abominaciones,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 19, NULL, 'tú, con todo, por tus muchas misericordias no los abandonaste en el desierto. La columna de nube no se apartó de ellos de día, para guiarlos por el camino, ni de noche la columna de fuego, para alumbrarles el camino por el cual habían de ir.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 20, NULL, 'Y enviaste tu buen Espíritu para enseñarles, y no retiraste tu maná de su boca, y agua les diste para su sed.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 21, NULL, 'Los sustentaste cuarenta años en el desierto; de ninguna cosa tuvieron necesidad; sus vestidos no se envejecieron, ni se hincharon sus pies.', 0, 'spa', 'RVR1960', NULL);\n"
;

  public static final String SQL_PARTE_2 = 
    "INSERT INTO Versiculo (\n" +
    "    codLengua_vscl, codVersion_vscl, codLibro_vscl, codCapitulo_vscl, codVersiculo_vscl, encabezado_vscl,\n" +
    "    contenido_vscl,\n" +
    "    parrafo_vscl, codLengua_vscl_ltr, codVersion_vscl_ltr, codLectura_vscl_ltr)\n" +
    "VALUES\n" +
    "('spa', 'RVR1960', 'Neh', 9, 22, NULL, 'Y les diste reinos y pueblos, y los repartiste por distritos; y poseyeron la tierra de Sehón, la tierra del rey de Hesbón, y la tierra de Og rey de Basán.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 23, NULL, 'Multiplicaste sus hijos como las estrellas del cielo, y los llevaste a la tierra de la cual habías dicho a sus padres que habían de entrar a poseerla.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 24, NULL, 'Y los hijos vinieron y poseyeron la tierra, y humillaste delante de ellos a los moradores del país, a los cananeos, los cuales entregaste en su mano, y a sus reyes, y a los pueblos de la tierra, para que hiciesen de ellos como quisieran.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 25, NULL, 'Y tomaron ciudades fortificadas y tierra fértil, y heredaron casas llenas de todo bien, cisternas hechas, viñas y olivares, y muchos árboles frutales; comieron, se saciaron, y se deleitaron en tu gran bondad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 26, NULL, 'Pero te provocaron a ira, y se rebelaron contra ti, y echaron tu ley tras sus espaldas, y mataron a tus profetas que protestaban contra ellos para convertirlos a ti, e hicieron grandes abominaciones.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 27, NULL, 'Entonces los entregaste en mano de sus enemigos, los cuales los afligieron. Pero en el tiempo de su tribulación clamaron a ti, y tú desde los cielos los oíste; y según tu gran misericordia les enviaste libertadores para que los salvasen de mano de sus enemigos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 28, NULL, 'Pero una vez que tenían paz, volvían a hacer lo malo delante de ti, por lo cual los abandonaste en mano de sus enemigos que los dominaron; pero volvían y clamaban otra vez a ti, y tú desde los cielos los oías y según tus misericordias muchas veces los libraste.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 29, NULL, 'Les amonestaste a que se volviesen a tu ley; mas ellos se llenaron de soberbia, y no oyeron tus mandamientos, sino que pecaron contra tus juicios, los cuales si el hombre hiciere, en ellos vivirá; se rebelaron, endurecieron su cerviz, y no escucharon.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 30, NULL, 'Les soportaste por muchos años, y les testificaste con tu Espíritu por medio de tus profetas, pero no escucharon; por lo cual los entregaste en mano de los pueblos de la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 31, NULL, 'Mas por tus muchas misericordias no los consumiste, ni los desamparaste; porque eres Dios clemente y misericordioso.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 32, NULL, 'Ahora pues, Dios nuestro, Dios grande, fuerte, temible, que guardas el pacto y la misericordia, no sea tenido en poco delante de ti todo el sufrimiento que ha alcanzado a nuestros reyes, a nuestros príncipes, a nuestros sacerdotes, a nuestros profetas, a nuestros padres y a todo tu pueblo, desde los días de los reyes de Asiria hasta este día.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 33, NULL, 'Pero tú eres justo en todo lo que ha venido sobre nosotros; porque rectamente has hecho, mas nosotros hemos hecho lo malo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 34, NULL, 'Nuestros reyes, nuestros príncipes, nuestros sacerdotes y nuestros padres no pusieron por obra tu ley, ni atendieron a tus mandamientos y a tus testimonios con que les amonestabas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 35, NULL, 'Y ellos en su reino y en tu mucho bien que les diste, y en la tierra espaciosa y fértil que entregaste delante de ellos, no te sirvieron, ni se convirtieron de sus malas obras.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 36, NULL, 'He aquí que hoy somos siervos; henos aquí, siervos en la tierra que diste a nuestros padres para que comiesen su fruto y su bien.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 37, NULL, 'Y se multiplica su fruto para los reyes que has puesto sobre nosotros por nuestros pecados, quienes se enseñorean sobre nuestros cuerpos, y sobre nuestros ganados, conforme a su voluntad, y estamos en grande angustia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 9, 38, 'Pacto del pueblo, de guardar la ley', 'A causa, pues, de todo esto, nosotros hacemos fiel promesa, y la escribimos, firmada por nuestros príncipes, por nuestros levitas y por nuestros sacerdotes.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 1, NULL, 'Los que firmaron fueron: Nehemías el gobernador, hijo de Hacalías, y Sedequías,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 2, NULL, 'Seraías, Azarías, Jeremías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 3, NULL, 'Pasur, Amarías, Malquías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 4, NULL, 'Hatús, Sebanías, Maluc,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 5, NULL, 'Harim, Meremot, Obadías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 6, NULL, 'Daniel, Ginetón, Baruc,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 7, NULL, 'Mesulam, Abías, Mijamín,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 8, NULL, 'Maazías, Bilgai y Semaías; estos eran sacerdotes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 9, NULL, 'Y los levitas: Jesúa hijo de Azanías, Binúi de los hijos de Henadad, Cadmiel,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 10, NULL, 'y sus hermanos Sebanías, Hodías, Kelita, Pelaías, Hanán,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 11, NULL, 'Micaía, Rehob, Hasabías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 12, NULL, 'Zacur, Serebías, Sebanías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 13, NULL, 'Hodías, Bani y Beninu.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 14, NULL, 'Los cabezas del pueblo: Paros, Pahat-moab, Elam, Zatu, Bani,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 15, NULL, 'Buni, Azgad, Bebai,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 16, NULL, 'Adonías, Bigvai, Adín,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 17, NULL, 'Ater, Ezequías, Azur,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 18, NULL, 'Hodías, Hasum, Bezai,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 19, NULL, 'Harif, Anatot, Nebai,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 20, NULL, 'Magpías, Mesulam, Hezir,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 21, NULL, 'Mesezabeel, Sadoc, Jadúa,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 22, NULL, 'Pelatías, Hanán, Anaías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 23, NULL, 'Oseas, Hananías, Hasub,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 24, NULL, 'Halohes, Pilha, Sobec,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 25, NULL, 'Rehum, Hasabna, Maasías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 26, NULL, 'Ahías, Hanán, Anán,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 27, NULL, 'Maluc, Harim y Baana.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 28, NULL, 'Y el resto del pueblo, los sacerdotes, levitas, porteros y cantores, los sirvientes del templo, y todos los que se habían apartado de los pueblos de las tierras a la ley de Dios, con sus mujeres, sus hijos e hijas, todo el que tenía comprensión y discernimiento,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 29, NULL, 'se reunieron con sus hermanos y sus principales, para protestar y jurar que andarían en la ley de Dios, que fue dada por Moisés siervo de Dios, y que guardarían y cumplirían todos los mandamientos, decretos y estatutos de Jehová nuestro Señor.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 30, NULL, 'Y que no daríamos nuestras hijas a los pueblos de la tierra, ni tomaríamos sus hijas para nuestros hijos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 31, NULL, 'Asimismo, que si los pueblos de la tierra trajesen a vender mercaderías y comestibles en día de reposo, nada tomaríamos de ellos en ese día ni en otro día santificado; y que el año séptimo dejaríamos descansar la tierra, y remitiríamos toda deuda.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 32, NULL, 'Nos impusimos además por ley, el cargo de contribuir cada año con la tercera parte de un siclo para la obra de la casa de nuestro Dios;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 33, NULL, 'para el pan de la proposición y para la ofrenda continua, para el holocausto continuo, los días de reposo, las nuevas lunas, las festividades, y para las cosas santificadas y los sacrificios de expiación por el pecado de Israel, y para todo el servicio de la casa de nuestro Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 34, NULL, 'Echamos también suertes los sacerdotes, los levitas y el pueblo, acerca de la ofrenda de la leña, para traerla a la casa de nuestro Dios, según las casas de nuestros padres, en los tiempos determinados cada año, para quemar sobre el altar de Jehová nuestro Dios, como está escrito en la ley.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 35, NULL, 'Y que cada año traeríamos a la casa de Jehová las primicias de nuestra tierra, y las primicias del fruto de todo árbol.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 36, NULL, 'Asimismo los primogénitos de nuestros hijos y de nuestros ganados, como está escrito en la ley; y que traeríamos los primogénitos de nuestras vacas y de nuestras ovejas a la casa de nuestro Dios, a los sacerdotes que ministran en la casa de nuestro Dios;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 37, NULL, 'que traeríamos también las primicias de nuestras masas, y nuestras ofrendas, y del fruto de todo árbol, y del vino y del aceite, para los sacerdotes, a las cámaras de la casa de nuestro Dios, y el diezmo de nuestra tierra para los levitas; y que los levitas recibirían las décimas de nuestras labores en todas las ciudades;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 38, NULL, 'y que estaría el sacerdote hijo de Aarón con los levitas, cuando los levitas recibiesen el diezmo; y que los levitas llevarían el diezmo del diezmo a la casa de nuestro Dios, a las cámaras de la casa del tesoro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 10, 39, NULL, 'Porque a las cámaras del tesoro han de llevar los hijos de Israel y los hijos de Leví la ofrenda del grano, del vino y del aceite; y allí estarán los utensilios del santuario, y los sacerdotes que ministran, los porteros y los cantores; y no abandonaremos la casa de nuestro Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 1, 'Los habitantes de Jerusalén', 'Habitaron los jefes del pueblo en Jerusalén; mas el resto del pueblo echó suertes para traer uno de cada diez para que morase en Jerusalén, ciudad santa, y las otras nueve partes en las otras ciudades.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 2, NULL, 'Y bendijo el pueblo a todos los varones que voluntariamente se ofrecieron para morar en Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 3, NULL, 'Estos son los jefes de la provincia que moraron en Jerusalén; pero en las ciudades de Judá habitaron cada uno en su posesión, en sus ciudades; los israelitas, los sacerdotes y levitas, los sirvientes del templo y los hijos de los siervos de Salomón.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 4, NULL, 'En Jerusalén, pues, habitaron algunos de los hijos de Judá y de los hijos de Benjamín. De los hijos de Judá: Ataías hijo de Uzías, hijo de Zacarías, hijo de Amarías, hijo de Sefatías, hijo de Mahalaleel, de los hijos de Fares,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 5, NULL, 'y Maasías hijo de Baruc, hijo de Colhoze, hijo de Hazaías, hijo de Adaías, hijo de Joiarib, hijo de Zacarías, hijo de Siloni.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 6, NULL, 'Todos los hijos de Fares que moraron en Jerusalén fueron cuatrocientos sesenta y ocho hombres fuertes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 7, NULL, 'Estos son los hijos de Benjamín: Salú hijo de Mesulam, hijo de Joed, hijo de Pedaías, hijo de Colaías, hijo de Maasías, hijo de Itiel, hijo de Jesaías.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 8, NULL, 'Y tras él Gabai y Salai, novecientos veintiocho.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 9, NULL, 'Y Joel hijo de Zicri era el prefecto de ellos, y Judá hijo de Senúa el segundo en la ciudad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 10, NULL, 'De los sacerdotes: Jedaías hijo de Joiarib, Jaquín,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 11, NULL, 'Seraías hijo de Hilcías, hijo de Mesulam, hijo de Sadoc, hijo de Meraiot, hijo de Ahitob, príncipe de la casa de Dios,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 12, NULL, 'y sus hermanos, los que hacían la obra de la casa, ochocientos veintidós; y Adaías hijo de Jeroham, hijo de Pelalías, hijo de Amsi, hijo de Zacarías, hijo de Pasur, hijo de Malquías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 13, NULL, 'y sus hermanos, jefes de familias, doscientos cuarenta y dos; y Amasai hijo de Azareel, hijo de Azai, hijo de Mesilemot, hijo de Imer,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 14, NULL, 'y sus hermanos, hombres de gran vigor, ciento veintiocho, el jefe de los cuales era Zabdiel hijo de Gedolim.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 15, NULL, 'De los levitas: Semaías hijo de Hasub, hijo de Azricam, hijo de Hasabías, hijo de Buni;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 16, NULL, 'Sabetai y Jozabad, de los principales de los levitas, capataces de la obra exterior de la casa de Dios;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 17, NULL, 'y Matanías hijo de Micaía, hijo de Zabdi, hijo de Asaf, el principal, el que empezaba las alabanzas y acción de gracias al tiempo de la oración; Bacbuquías el segundo de entre sus hermanos; y Abda hijo de Samúa, hijo de Galal, hijo de Jedutún.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 18, NULL, 'Todos los levitas en la santa ciudad eran doscientos ochenta y cuatro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 19, NULL, 'Los porteros, Acub, Talmón y sus hermanos, guardas en las puertas, ciento setenta y dos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 20, NULL, 'Y el resto de Israel, de los sacerdotes y de los levitas, en todas las ciudades de Judá, cada uno en su heredad.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 21, NULL, 'Los sirvientes del templo habitaban en Ofel; y Ziha y Gispa tenían autoridad sobre los sirvientes del templo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 22, NULL, 'Y el jefe de los levitas en Jerusalén era Uzi hijo de Bani, hijo de Hasabías, hijo de Matanías, hijo de Micaía, de los hijos de Asaf, cantores, sobre la obra de la casa de Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 23, NULL, 'Porque había mandamiento del rey acerca de ellos, y distribución para los cantores para cada día.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 24, NULL, 'Y Petaías hijo de Mesezabeel, de los hijos de Zera hijo de Judá, estaba al servicio del rey en todo negocio del pueblo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 25, 'Lugares habitados fuera de Jerusalén', 'Tocante a las aldeas y sus tierras, algunos de los hijos de Judá habitaron en Quiriat-arba y sus aldeas, en Dibón y sus aldeas, en Jecabseel y sus aldeas,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 26, NULL, 'en Jesúa, Molada y Bet-pelet,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 27, NULL, 'en Hazar-sual, en Beerseba y sus aldeas,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 28, NULL, 'en Siclag, en Mecona y sus aldeas,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 29, NULL, 'en En-rimón, en Zora, en Jarmut,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 30, NULL, 'en Zanoa, en Adulam y sus aldeas, en Laquis y sus tierras, y en Azeca y sus aldeas. Y habitaron desde Beerseba hasta el valle de Hinom.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 31, NULL, 'Y los hijos de Benjamín habitaron desde Geba, en Micmas, en Aía, en Bet-el y sus aldeas,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 32, NULL, 'en Anatot, Nob, Ananías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 33, NULL, 'Hazor, Ramá, Gitaim,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 34, NULL, 'Hadid, Seboim, Nebalat,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 35, NULL, 'Lod, y Ono, valle de los artífices;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 11, 36, NULL, 'y algunos de los levitas, en los repartimientos de Judá y de Benjamín.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 1, 'Sacerdotes y levitas', 'Estos son los sacerdotes y levitas que subieron con Zorobabel hijo de Salatiel, y con Jesúa: Seraías, Jeremías, Esdras,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 2, NULL, 'Amarías, Maluc, Hatús,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 3, NULL, 'Secanías, Rehum, Meremot,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 4, NULL, 'Iddo, Gineto, Abías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 5, NULL, 'Mijamín, Maadías, Bilga,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 6, NULL, 'Semaías, Joiarib, Jedaías,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 7, NULL, 'Salú, Amoc, Hilcías y Jedaías. Estos eran los príncipes de los sacerdotes y sus hermanos en los días de Jesúa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 8, NULL, 'Y los levitas: Jesúa, Binúi, Cadmiel, Serebías, Judá y Matanías, que con sus hermanos oficiaba en los cantos de alabanza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 9, NULL, 'Y Bacbuquías y Uni, sus hermanos, cada cual en su ministerio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 10, NULL, 'Jesúa engendró a Joiacim, y Joiacim engendró a Eliasib, y Eliasib engendró a Joiada;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 11, NULL, 'Joiada engendró a Jonatán, y Jonatán engendró a Jadúa.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 12, NULL, 'Y en los días de Joiacim los sacerdotes jefes de familias fueron: de Seraías, Meraías; de Jeremías, Hananías;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 13, NULL, 'de Esdras, Mesulam; de Amarías, Johanán;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 14, NULL, 'de Melicú, Jonatán; de Sebanías, José;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 15, NULL, 'de Harim, Adna; de Meraiot, Helcai;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 16, NULL, 'de Iddo, Zacarías; de Ginetón, Mesulam;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 17, NULL, 'de Abías, Zicri; de Miniamín, de Moadías, Piltai;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 18, NULL, 'de Bilga, Samúa; de Semaías, Jonatán;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 19, NULL, 'de Joiarib, Matenai; de Jedaías, Uzi;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 20, NULL, 'de Salai, Calai; de Amoc, Eber;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 21, NULL, 'de Hilcías, Hasabías; de Jedaías, Natanael.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 22, NULL, 'Los levitas en días de Eliasib, de Joiada, de Johanán y de Jadúa fueron inscritos por jefes de familias; también los sacerdotes, hasta el reinado de Darío el persa.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 23, NULL, 'Los hijos de Leví, jefes de familias, fueron inscritos en el libro de las crónicas hasta los días de Johanán hijo de Eliasib.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 24, NULL, 'Los principales de los levitas: Hasabías, Serebías, Jesúa hijo de Cadmiel, y sus hermanos delante de ellos, para alabar y dar gracias, conforme al estatuto de David varón de Dios, guardando su turno.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 25, NULL, 'Matanías, Bacbuquías, Obadías, Mesulam, Talmón y Acub, guardas, eran porteros para la guardia a las entradas de las puertas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 26, NULL, 'Estos fueron en los días de Joiacim hijo de Jesúa, hijo de Josadac, y en los días del gobernador Nehemías y del sacerdote Esdras, escriba.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 27, 'Dedicación del muro', 'Para la dedicación del muro de Jerusalén, buscaron a los levitas de todos sus lugares para traerlos a Jerusalén, para hacer la dedicación y la fiesta con alabanzas y con cánticos, con címbalos, salterios y cítaras.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 28, NULL, 'Y fueron reunidos los hijos de los cantores, así de la región alrededor de Jerusalén como de las aldeas de los netofatitas;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 29, NULL, 'y de la casa de Gilgal, y de los campos de Geba y de Azmavet; porque los cantores se habían edificado aldeas alrededor de Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 30, NULL, 'Y se purificaron los sacerdotes y los levitas; y purificaron al pueblo, y las puertas, y el muro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 31, NULL, 'Hice luego subir a los príncipes de Judá sobre el muro, y puse dos coros grandes que fueron en procesión; el uno a la derecha, sobre el muro, hacia la puerta del Muladar.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 32, NULL, 'E iba tras de ellos Osaías con la mitad de los príncipes de Judá,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 33, NULL, 'y Azarías, Esdras, Mesulam,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 34, NULL, 'Judá y Benjamín, Semaías y Jeremías.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 35, NULL, 'Y de los hijos de los sacerdotes iban con trompetas Zacarías hijo de Jonatán, hijo de Semaías, hijo de Matanías, hijo de Micaías, hijo de Zacur, hijo de Asaf;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 36, NULL, 'y sus hermanos Semaías, Azarael, Milalai, Gilalai, Maai, Natanael, Judá y Hanani, con los instrumentos musicales de David varón de Dios; y el escriba Esdras delante de ellos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 37, NULL, 'Y a la puerta de la Fuente, en frente de ellos, subieron por las gradas de la ciudad de David, por la subida del muro, desde la casa de David hasta la puerta de las Aguas, al oriente.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 38, NULL, 'El segundo coro iba del lado opuesto, y yo en pos de él, con la mitad del pueblo sobre el muro, desde la torre de los Hornos hasta el muro ancho;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 39, NULL, 'y desde la puerta de Efraín hasta la puerta Vieja y a la puerta del Pescado, y la torre de Hananeel, y la torre de Hamea, hasta la puerta de las Ovejas; y se detuvieron en la puerta de la Cárcel.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 40, NULL, 'Llegaron luego los dos coros a la casa de Dios; y yo, y la mitad de los oficiales conmigo,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 41, NULL, 'y los sacerdotes Eliacim, Maaseías, Miniamín, Micaías, Elioenai, Zacarías y Hananías, con trompetas;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 42, NULL, 'y Maasías, Semaías, Eleazar, Uzi, Johanán, Malquías, Elam y Ezer. Y los cantores cantaban en alta voz, e Izrahías era el director.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 43, NULL, 'Y sacrificaron aquel día numerosas víctimas, y se regocijaron, porque Dios los había recreado con grande contentamiento; se alegraron también las mujeres y los niños; y el alborozo de Jerusalén fue oído desde lejos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 44, 'Porciones para sacerdotes y levitas', 'En aquel día fueron puestos varones sobre las cámaras de los tesoros, de las ofrendas, de las primicias y de los diezmos, para recoger en ellas, de los ejidos de las ciudades, las porciones legales para los sacerdotes y levitas; porque era grande el gozo de Judá con respecto a los sacerdotes y levitas que servían.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 45, NULL, 'Y habían cumplido el servicio de su Dios, y el servicio de la expiación, como también los cantores y los porteros, conforme al estatuto de David y de Salomón su hijo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 46, NULL, 'Porque desde el tiempo de David y de Asaf, ya de antiguo, había un director de cantores para los cánticos y alabanzas y acción de gracias a Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 12, 47, NULL, 'Y todo Israel en días de Zorobabel y en días de Nehemías daba alimentos a los cantores y a los porteros, cada cosa en su día; consagraban asimismo sus porciones a los levitas, y los levitas consagraban parte a los hijos de Aarón.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 1, 'Reformas de Nehemías', 'Aquel día se leyó en el libro de Moisés, oyéndolo el pueblo, y fue hallado escrito en él que los amonitas y moabitas no debían entrar jamás en la congregación de Dios,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 2, NULL, 'por cuanto no salieron a recibir a los hijos de Israel con pan y agua, sino que dieron dinero a Balaam para que los maldijera; mas nuestro Dios volvió la maldición en bendición.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 3, NULL, 'Cuando oyeron, pues, la ley, separaron de Israel a todos los mezclados con extranjeros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 4, NULL, 'Y antes de esto el sacerdote Eliasib, siendo jefe de la cámara de la casa de nuestro Dios, había emparentado con Tobías,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 5, NULL, 'y le había hecho una gran cámara, en la cual guardaban antes las ofrendas, el incienso, los utensilios, el diezmo del grano, del vino y del aceite, que estaba mandado dar a los levitas, a los cantores y a los porteros, y la ofrenda de los sacerdotes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 6, NULL, 'Mas a todo esto, yo no estaba en Jerusalén, porque en el año treinta y dos de Artajerjes rey de Babilonia fui al rey; y al cabo de algunos días pedí permiso al rey', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 7, NULL, 'para volver a Jerusalén; y entonces supe del mal que había hecho Eliasib por consideración a Tobías, haciendo para él una cámara en los atrios de la casa de Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 8, NULL, 'Y me dolió en gran manera; y arrojé todos los muebles de la casa de Tobías fuera de la cámara,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 9, NULL, 'y dije que limpiasen las cámaras, e hice volver allí los utensilios de la casa de Dios, las ofrendas y el incienso.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 10, NULL, 'Encontré asimismo que las porciones para los levitas no les habían sido dadas, y que los levitas y cantores que hacían el servicio habían huido cada uno a su heredad.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 11, NULL, 'Entonces reprendí a los oficiales, y dije: ¿Por qué está la casa de Dios abandonada? Y los reuní y los puse en sus puestos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 12, NULL, 'Y todo Judá trajo el diezmo del grano, del vino y del aceite, a los almacenes.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 13, NULL, 'Y puse por mayordomos de ellos al sacerdote Selemías y al escriba Sadoc, y de los levitas a Pedaías; y al servicio de ellos a Hanán hijo de Zacur, hijo de Matanías; porque eran tenidos por fieles, y ellos tenían que repartir a sus hermanos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 14, NULL, 'Acuérdate de mí, oh Dios, en orden a esto, y no borres mis misericordias que hice en la casa de mi Dios, y en su servicio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 15, NULL, 'En aquellos días vi en Judá a algunos que pisaban en lagares en el día de reposo, y que acarreaban haces, y cargaban asnos con vino, y también de uvas, de higos y toda suerte de carga, y que traían a Jerusalén en día de reposo; y los amonesté acerca del día en que vendían las provisiones.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 16, NULL, 'También había en la ciudad tirios que traían pescado y toda mercadería, y vendían en día de reposo a los hijos de Judá en Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 17, NULL, 'Y reprendí a los señores de Judá y les dije: ¿Qué mala cosa es esta que vosotros hacéis, profanando así el día de reposo?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 18, NULL, '¿No hicieron así vuestros padres, y trajo nuestro Dios todo este mal sobre nosotros y sobre esta ciudad? ¿Y vosotros añadís ira sobre Israel profanando el día de reposo?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 19, NULL, 'Sucedió, pues, que cuando iba oscureciendo a las puertas de Jerusalén antes del día de reposo, dije que se cerrasen las puertas, y ordené que no las abriesen hasta después del día de reposo; y puse a las puertas algunos de mis criados, para que en día de reposo no introdujeran carga.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 20, NULL, 'Y se quedaron fuera de Jerusalén una y dos veces los negociantes y los que vendían toda especie de mercancía.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 21, NULL, 'Y les amonesté y les dije: ¿Por qué os quedáis vosotros delante del muro? Si lo hacéis otra vez, os echaré mano. Desde entonces no vinieron en día de reposo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 22, NULL, 'Y dije a los levitas que se purificasen y viniesen a guardar las puertas, para santificar el día del reposo. También por esto acuérdate de mí, Dios mío, y perdóname según la grandeza de tu misericordia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 23, NULL, 'Vi asimismo en aquellos días a judíos que habían tomado mujeres de Asdod, amonitas, y moabitas;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 24, NULL, 'y la mitad de sus hijos hablaban la lengua de Asdod, porque no sabían hablar judaico, sino que hablaban conforme a la lengua de cada pueblo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 25, NULL, 'Y reñí con ellos, y los maldije, y herí a algunos de ellos, y les arranqué los cabellos, y les hice jurar, diciendo: No daréis vuestras hijas a sus hijos, y no tomaréis de sus hijas para vuestros hijos, ni para vosotros mismos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 26, NULL, '¿No pecó por esto Salomón, rey de Israel? Bien que en muchas naciones no hubo rey como él, que era amado de su Dios, y Dios lo había puesto por rey sobre todo Israel, aun a él le hicieron pecar las mujeres extranjeras.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 27, NULL, '¿Y obedeceremos a vosotros para cometer todo este mal tan grande de prevaricar contra nuestro Dios, tomando mujeres extranjeras?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 28, NULL, 'Y uno de los hijos de Joiada hijo del sumo sacerdote Eliasib era yerno de Sanbalat horonita; por tanto, lo ahuyenté de mí.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 29, NULL, 'Acuérdate de ellos, Dios mío, contra los que contaminan el sacerdocio, y el pacto del sacerdocio y de los levitas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 30, NULL, 'Los limpié, pues, de todo extranjero, y puse a los sacerdotes y levitas por sus grupos, a cada uno en su servicio;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Neh', 13, 31, NULL, 'y para la ofrenda de la leña en los tiempos señalados, y para las primicias. Acuérdate de mí, Dios mío, para bien.', 0, 'spa', 'RVR1960', NULL);\n"
;

}