package com.orellano.biblia360.daoSQLite.sql.spa;

public final class LoadDaniel {
  public LoadDaniel() {}
  public static final String SQL_PARTE_1 = 
    "INSERT INTO Versiculo (\n" +
    "    codLengua_vscl, codVersion_vscl, codLibro_vscl, codCapitulo_vscl, codVersiculo_vscl, encabezado_vscl,\n" +
    "    contenido_vscl,\n" +
    "    parrafo_vscl, codLengua_vscl_ltr, codVersion_vscl_ltr, codLectura_vscl_ltr)\n" +
    "VALUES\n" +
    "('spa', 'RVR1960', 'Dn', 1, 1, 'Daniel y sus compañeros en Babilonia', 'En el año tercero del reinado de Joacim rey de Judá, vino Nabucodonosor rey de Babilonia a Jerusalén, y la sitió.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 2, NULL, 'Y el Señor entregó en sus manos a Joacim rey de Judá, y parte de los utensilios de la casa de Dios; y los trajo a tierra de Sinar, a la casa de su dios, y colocó los utensilios en la casa del tesoro de su dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 3, NULL, 'Y dijo el rey a Aspenaz, jefe de sus eunucos, que trajese de los hijos de Israel, del linaje real de los príncipes,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 4, NULL, 'muchachos en quienes no hubiese tacha alguna, de buen parecer, enseñados en toda sabiduría, sabios en ciencia y de buen entendimiento, e idóneos para estar en el palacio del rey; y que les enseñase las letras y la lengua de los caldeos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 5, NULL, 'Y les señaló el rey ración para cada día, de la provisión de la comida del rey, y del vino que él bebía; y que los criase tres años, para que al fin de ellos se presentasen delante del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 6, NULL, 'Entre estos estaban Daniel, Ananías, Misael y Azarías, de los hijos de Judá.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 7, NULL, 'A estos el jefe de los eunucos puso nombres: puso a Daniel, Beltsasar; a Ananías, Sadrac; a Misael, Mesac; y a Azarías, Abed-nego.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 8, NULL, 'Y Daniel propuso en su corazón no contaminarse con la porción de la comida del rey, ni con el vino que él bebía; pidió, por tanto, al jefe de los eunucos que no se le obligase a contaminarse.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 9, NULL, 'Y puso Dios a Daniel en gracia y en buena voluntad con el jefe de los eunucos;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 10, NULL, 'y dijo el jefe de los eunucos a Daniel: Temo a mi señor el rey, que señaló vuestra comida y vuestra bebida; pues luego que él vea vuestros rostros más pálidos que los de los muchachos que son semejantes a vosotros, condenaréis para con el rey mi cabeza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 11, NULL, 'Entonces dijo Daniel a Melsar, que estaba puesto por el jefe de los eunucos sobre Daniel, Ananías, Misael y Azarías:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 12, NULL, 'Te ruego que hagas la prueba con tus siervos por diez días, y nos den legumbres a comer, y agua a beber.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 13, NULL, 'Compara luego nuestros rostros con los rostros de los muchachos que comen de la ración de la comida del rey, y haz después con tus siervos según veas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 14, NULL, 'Consintió, pues, con ellos en esto, y probó con ellos diez días.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 15, NULL, 'Y al cabo de los diez días pareció el rostro de ellos mejor y más robusto que el de los otros muchachos que comían de la porción de la comida del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 16, NULL, 'Así, pues, Melsar se llevaba la porción de la comida de ellos y el vino que habían de beber, y les daba legumbres.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 17, NULL, 'A estos cuatro muchachos Dios les dio conocimiento e inteligencia en todas las letras y ciencias; y Daniel tuvo entendimiento en toda visión y sueños.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 18, NULL, 'Pasados, pues, los días al fin de los cuales había dicho el rey que los trajesen, el jefe de los eunucos los trajo delante de Nabucodonosor.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 19, NULL, 'Y el rey habló con ellos, y no fueron hallados entre todos ellos otros como Daniel, Ananías, Misael y Azarías; así, pues, estuvieron delante del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 20, NULL, 'En todo asunto de sabiduría e inteligencia que el rey les consultó, los halló diez veces mejores que todos los magos y astrólogos que había en todo su reino.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 1, 21, NULL, 'Y continuó Daniel hasta el año primero del rey Ciro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 1, 'Daniel interpreta el sueño de Nabucodonosor', 'En el segundo año del reinado de Nabucodonosor, tuvo Nabucodonosor sueños, y se perturbó su espíritu, y se le fue el sueño.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 2, NULL, 'Hizo llamar el rey a magos, astrólogos, encantadores y caldeos, para que le explicasen sus sueños. Vinieron, pues, y se presentaron delante del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 3, NULL, 'Y el rey les dijo: He tenido un sueño, y mi espíritu se ha turbado por saber el sueño.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 4, NULL, 'Entonces hablaron los caldeos al rey en lengua aramea: Rey, para siempre vive; di el sueño a tus siervos, y te mostraremos la interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 5, NULL, 'Respondió el rey y dijo a los caldeos: El asunto lo olvidé; si no me mostráis el sueño y su interpretación, seréis hechos pedazos, y vuestras casas serán convertidas en muladares.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 6, NULL, 'Y si me mostrareis el sueño y su interpretación, recibiréis de mí dones y favores y gran honra. Decidme, pues, el sueño y su interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 7, NULL, 'Respondieron por segunda vez, y dijeron: Diga el rey el sueño a sus siervos, y le mostraremos la interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 8, NULL, 'El rey respondió y dijo: Yo conozco ciertamente que vosotros ponéis dilaciones, porque veis que el asunto se me ha ido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 9, NULL, 'Si no me mostráis el sueño, una sola sentencia hay para vosotros. Ciertamente preparáis respuesta mentirosa y perversa que decir delante de mí, entre tanto que pasa el tiempo. Decidme, pues, el sueño, para que yo sepa que me podéis dar su interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 10, NULL, 'Los caldeos respondieron delante del rey, y dijeron: No hay hombre sobre la tierra que pueda declarar el asunto del rey; además de esto, ningún rey, príncipe ni señor preguntó cosa semejante a ningún mago ni astrólogo ni caldeo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 11, NULL, 'Porque el asunto que el rey demanda es difícil, y no hay quien lo pueda declarar al rey, salvo los dioses cuya morada no es con la carne.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 12, NULL, 'Por esto el rey con ira y con gran enojo mandó que matasen a todos los sabios de Babilonia.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 13, NULL, 'Y se publicó el edicto de que los sabios fueran llevados a la muerte; y buscaron a Daniel y a sus compañeros para matarlos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 14, NULL, 'Entonces Daniel habló sabia y prudentemente a Arioc, capitán de la guardia del rey, que había salido para matar a los sabios de Babilonia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 15, NULL, 'Habló y dijo a Arioc capitán del rey: ¿Cuál es la causa de que este edicto se publique de parte del rey tan apresuradamente? Entonces Arioc hizo saber a Daniel lo que había.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 16, NULL, 'Y Daniel entró y pidió al rey que le diese tiempo, y que él mostraría la interpretación al rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 17, NULL, 'Luego se fue Daniel a su casa e hizo saber lo que había a Ananías, Misael y Azarías, sus compañeros,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 18, NULL, 'para que pidiesen misericordias del Dios del cielo sobre este misterio, a fin de que Daniel y sus compañeros no pereciesen con los otros sabios de Babilonia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 19, NULL, 'Entonces el secreto fue revelado a Daniel en visión de noche, por lo cual bendijo Daniel al Dios del cielo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 20, NULL, 'Y Daniel habló y dijo: Sea bendito el nombre de Dios de siglos en siglos, porque suyos son el poder y la sabiduría.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 21, NULL, 'Él muda los tiempos y las edades; quita reyes, y pone reyes; da la sabiduría a los sabios, y la ciencia a los entendidos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 22, NULL, 'Él revela lo profundo y lo escondido; conoce lo que está en tinieblas, y con él mora la luz.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 23, NULL, 'A ti, oh Dios de mis padres, te doy gracias y te alabo, porque me has dado sabiduría y fuerza, y ahora me has revelado lo que te pedimos; pues nos has dado a conocer el asunto del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 24, NULL, 'Después de esto fue Daniel a Arioc, al cual el rey había puesto para matar a los sabios de Babilonia, y le dijo así: No mates a los sabios de Babilonia; llévame a la presencia del rey, y yo le mostraré la interpretación.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 25, NULL, 'Entonces Arioc llevó prontamente a Daniel ante el rey, y le dijo así: He hallado un varón de los deportados de Judá, el cual dará al rey la interpretación.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 26, NULL, 'Respondió el rey y dijo a Daniel, al cual llamaban Beltsasar: ¿Podrás tú hacerme conocer el sueño que vi, y su interpretación?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 27, NULL, 'Daniel respondió delante del rey, diciendo: El misterio que el rey demanda, ni sabios, ni astrólogos, ni magos ni adivinos lo pueden revelar al rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 28, NULL, 'Pero hay un Dios en los cielos, el cual revela los misterios, y él ha hecho saber al rey Nabucodonosor lo que ha de acontecer en los postreros días. He aquí tu sueño, y las visiones que has tenido en tu cama:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 29, NULL, 'Estando tú, oh rey, en tu cama, te vinieron pensamientos por saber lo que había de ser en lo por venir; y el que revela los misterios te mostró lo que ha de ser.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 30, NULL, 'Y a mí me ha sido revelado este misterio, no porque en mí haya más sabiduría que en todos los vivientes, sino para que se dé a conocer al rey la interpretación, y para que entiendas los pensamientos de tu corazón.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 31, NULL, 'Tú, oh rey, veías, y he aquí una gran imagen. Esta imagen, que era muy grande, y cuya gloria era muy sublime, estaba en pie delante de ti, y su aspecto era terrible.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 32, NULL, 'La cabeza de esta imagen era de oro fino; su pecho y sus brazos, de plata; su vientre y sus muslos, de bronce;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 33, NULL, 'sus piernas, de hierro; sus pies, en parte de hierro y en parte de barro cocido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 34, NULL, 'Estabas mirando, hasta que una piedra fue cortada, no con mano, e hirió a la imagen en sus pies de hierro y de barro cocido, y los desmenuzó.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 35, NULL, 'Entonces fueron desmenuzados también el hierro, el barro cocido, el bronce, la plata y el oro, y fueron como tamo de las eras del verano, y se los llevó el viento sin que de ellos quedara rastro alguno. Mas la piedra que hirió a la imagen fue hecha un gran monte que llenó toda la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 36, NULL, 'Este es el sueño; también la interpretación de él diremos en presencia del rey.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 37, NULL, 'Tú, oh rey, eres rey de reyes; porque el Dios del cielo te ha dado reino, poder, fuerza y majestad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 38, NULL, 'Y dondequiera que habitan hijos de hombres, bestias del campo y aves del cielo, él los ha entregado en tu mano, y te ha dado el dominio sobre todo; tú eres aquella cabeza de oro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 39, NULL, 'Y después de ti se levantará otro reino inferior al tuyo; y luego un tercer reino de bronce, el cual dominará sobre toda la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 40, NULL, 'Y el cuarto reino será fuerte como hierro; y como el hierro desmenuza y rompe todas las cosas, desmenuzará y quebrantará todo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 41, NULL, 'Y lo que viste de los pies y los dedos, en parte de barro cocido de alfarero y en parte de hierro, será un reino dividido; mas habrá en él algo de la fuerza del hierro, así como viste hierro mezclado con barro cocido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 42, NULL, 'Y por ser los dedos de los pies en parte de hierro y en parte de barro cocido, el reino será en parte fuerte, y en parte frágil.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 43, NULL, 'Así como viste el hierro mezclado con barro, se mezclarán por medio de alianzas humanas; pero no se unirán el uno con el otro, como el hierro no se mezcla con el barro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 44, NULL, 'Y en los días de estos reyes el Dios del cielo levantará un reino que no será jamás destruido, ni será el reino dejado a otro pueblo; desmenuzará y consumirá a todos estos reinos, pero él permanecerá para siempre,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 45, NULL, 'de la manera que viste que del monte fue cortada una piedra, no con mano, la cual desmenuzó el hierro, el bronce, el barro, la plata y el oro. El gran Dios ha mostrado al rey lo que ha de acontecer en lo por venir; y el sueño es verdadero, y fiel su interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 46, NULL, 'Entonces el rey Nabucodonosor se postró sobre su rostro y se humilló ante Daniel, y mandó que le ofreciesen presentes e incienso.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 47, NULL, 'El rey habló a Daniel, y dijo: Ciertamente el Dios vuestro es Dios de dioses, y Señor de los reyes, y el que revela los misterios, pues pudiste revelar este misterio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 48, NULL, 'Entonces el rey engrandeció a Daniel, y le dio muchos honores y grandes dones, y le hizo gobernador de toda la provincia de Babilonia, y jefe supremo de todos los sabios de Babilonia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 2, 49, NULL, 'Y Daniel solicitó del rey, y obtuvo que pusiera sobre los negocios de la provincia de Babilonia a Sadrac, Mesac y Abed-nego; y Daniel estaba en la corte del rey.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 1, 'Rescatados del horno de fuego', 'El rey Nabucodonosor hizo una estatua de oro cuya altura era de sesenta codos, y su anchura de seis codos; la levantó en el campo de Dura, en la provincia de Babilonia.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 2, NULL, 'Y envió el rey Nabucodonosor a que se reuniesen los sátrapas, los magistrados y capitanes, oidores, tesoreros, consejeros, jueces, y todos los gobernadores de las provincias, para que viniesen a la dedicación de la estatua que el rey Nabucodonosor había levantado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 3, NULL, 'Fueron, pues, reunidos los sátrapas, magistrados, capitanes, oidores, tesoreros, consejeros, jueces, y todos los gobernadores de las provincias, a la dedicación de la estatua que el rey Nabucodonosor había levantado; y estaban en pie delante de la estatua que había levantado el rey Nabucodonosor.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 4, NULL, 'Y el pregonero anunciaba en alta voz: Mándase a vosotros, oh pueblos, naciones y lenguas,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 5, NULL, 'que al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña y de todo instrumento de música, os postréis y adoréis la estatua de oro que el rey Nabucodonosor ha levantado;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 6, NULL, 'y cualquiera que no se postre y adore, inmediatamente será echado dentro de un horno de fuego ardiendo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 7, NULL, 'Por lo cual, al oír todos los pueblos el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña y de todo instrumento de música, todos los pueblos, naciones y lenguas se postraron y adoraron la estatua de oro que el rey Nabucodonosor había levantado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 8, NULL, 'Por esto en aquel tiempo algunos varones caldeos vinieron y acusaron maliciosamente a los judíos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 9, NULL, 'Hablaron y dijeron al rey Nabucodonosor: Rey, para siempre vive.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 10, NULL, 'Tú, oh rey, has dado una ley que todo hombre, al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña y de todo instrumento de música, se postre y adore la estatua de oro;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 11, NULL, 'y el que no se postre y adore, sea echado dentro de un horno de fuego ardiendo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 12, NULL, 'Hay unos varones judíos, los cuales pusiste sobre los negocios de la provincia de Babilonia: Sadrac, Mesac y Abed-nego; estos varones, oh rey, no te han respetado; no adoran tus dioses, ni adoran la estatua de oro que has levantado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 13, NULL, 'Entonces Nabucodonosor dijo con ira y con enojo que le trajesen a Sadrac, Mesac y Abed-nego. Al instante fueron traídos estos varones delante del rey.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 14, NULL, 'Habló Nabucodonosor y les dijo: ¿Es verdad, Sadrac, Mesac y Abed-nego, que vosotros no honráis a mi dios, ni adoráis la estatua de oro que he levantado?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 15, NULL, 'Ahora, pues, ¿estáis dispuestos para que al oír el son de la bocina, de la flauta, del tamboril, del arpa, del salterio, de la zampoña y de todo instrumento de música, os postréis y adoréis la estatua que he hecho? Porque si no la adorareis, en la misma hora seréis echados en medio de un horno de fuego ardiendo; ¿y qué dios será aquel que os libre de mis manos?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 16, NULL, 'Sadrac, Mesac y Abed-nego respondieron al rey Nabucodonosor, diciendo: No es necesario que te respondamos sobre este asunto.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 17, NULL, 'He aquí nuestro Dios a quien servimos puede librarnos del horno de fuego ardiendo; y de tu mano, oh rey, nos librará.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 18, NULL, 'Y si no, sepas, oh rey, que no serviremos a tus dioses, ni tampoco adoraremos la estatua que has levantado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 19, NULL, 'Entonces Nabucodonosor se llenó de ira, y se demudó el aspecto de su rostro contra Sadrac, Mesac y Abed-nego, y ordenó que el horno se calentase siete veces más de lo acostumbrado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 20, NULL, 'Y mandó a hombres muy vigorosos que tenía en su ejército, que atasen a Sadrac, Mesac y Abed-nego, para echarlos en el horno de fuego ardiendo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 21, NULL, 'Entonces estos varones fueron atados con sus mantos, sus calzas, sus turbantes y sus vestidos, y fueron echados dentro del horno de fuego ardiendo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 22, NULL, 'Y como la orden del rey era apremiante, y lo habían calentado mucho, la llama del fuego mató a aquellos que habían alzado a Sadrac, Mesac y Abed-nego.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 23, NULL, 'Y estos tres varones, Sadrac, Mesac y Abed-nego, cayeron atados dentro del horno de fuego ardiendo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 24, NULL, 'Entonces el rey Nabucodonosor se espantó, y se levantó apresuradamente y dijo a los de su consejo: ¿No echaron a tres varones atados dentro del fuego? Ellos respondieron al rey: Es verdad, oh rey.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 25, NULL, 'Y él dijo: He aquí yo veo cuatro varones sueltos, que se pasean en medio del fuego sin sufrir ningún daño; y el aspecto del cuarto es semejante a hijo de los dioses.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 26, NULL, 'Entonces Nabucodonosor se acercó a la puerta del horno de fuego ardiendo, y dijo: Sadrac, Mesac y Abed-nego, siervos del Dios Altísimo, salid y venid. Entonces Sadrac, Mesac y Abed-nego salieron de en medio del fuego.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 27, NULL, 'Y se juntaron los sátrapas, los gobernadores, los capitanes y los consejeros del rey, para mirar a estos varones, cómo el fuego no había tenido poder alguno sobre sus cuerpos, ni aun el cabello de sus cabezas se había quemado; sus ropas estaban intactas, y ni siquiera olor de fuego tenían.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 28, NULL, 'Entonces Nabucodonosor dijo: Bendito sea el Dios de ellos, de Sadrac, Mesac y Abed-nego, que envió su ángel y libró a sus siervos que confiaron en él, y que no cumplieron el edicto del rey, y entregaron sus cuerpos antes que servir y adorar a otro dios que su Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 29, NULL, 'Por lo tanto, decreto que todo pueblo, nación o lengua que dijere blasfemia contra el Dios de Sadrac, Mesac y Abed-nego, sea descuartizado, y su casa convertida en muladar; por cuanto no hay dios que pueda librar como este.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 3, 30, NULL, 'Entonces el rey engrandeció a Sadrac, Mesac y Abed-nego en la provincia de Babilonia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 1, 'La locura de Nabucodonosor', 'Nabucodonosor rey, a todos los pueblos, naciones y lenguas que moran en toda la tierra: Paz os sea multiplicada.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 2, NULL, 'Conviene que yo declare las señales y milagros que el Dios Altísimo ha hecho conmigo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 3, NULL, '¡Cuán grandes son sus señales, y cuán potentes sus maravillas! Su reino, reino sempiterno, y su señorío de generación en generación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 4, NULL, 'Yo Nabucodonosor estaba tranquilo en mi casa, y floreciente en mi palacio.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 5, NULL, 'Vi un sueño que me espantó, y tendido en cama, las imaginaciones y visiones de mi cabeza me turbaron.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 6, NULL, 'Por esto mandé que vinieran delante de mí todos los sabios de Babilonia, para que me mostrasen la interpretación del sueño.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 7, NULL, 'Y vinieron magos, astrólogos, caldeos y adivinos, y les dije el sueño, pero no me pudieron mostrar su interpretación,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 8, NULL, 'hasta que entró delante de mí Daniel, cuyo nombre es Beltsasar, como el nombre de mi dios, y en quien mora el espíritu de los dioses santos. Conté delante de él el sueño, diciendo:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 9, NULL, 'Beltsasar, jefe de los magos, ya que he entendido que hay en ti espíritu de los dioses santos, y que ningún misterio se te esconde, declárame las visiones de mi sueño que he visto, y su interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 10, NULL, 'Estas fueron las visiones de mi cabeza mientras estaba en mi cama: Me parecía ver en medio de la tierra un árbol, cuya altura era grande.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 11, NULL, 'Crecía este árbol, y se hacía fuerte, y su copa llegaba hasta el cielo, y se le alcanzaba a ver desde todos los confines de la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 12, NULL, 'Su follaje era hermoso y su fruto abundante, y había en él alimento para todos. Debajo de él se ponían a la sombra las bestias del campo, y en sus ramas hacían morada las aves del cielo, y se mantenía de él toda carne.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 13, NULL, 'Vi en las visiones de mi cabeza mientras estaba en mi cama, que he aquí un vigilante y santo descendía del cielo.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 14, NULL, 'Y clamaba fuertemente y decía así: Derribad el árbol, y cortad sus ramas, quitadle el follaje, y dispersad su fruto; váyanse las bestias que están debajo de él, y las aves de sus ramas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 15, NULL, 'Mas la cepa de sus raíces dejaréis en la tierra, con atadura de hierro y de bronce entre la hierba del campo; sea mojado con el rocío del cielo, y con las bestias sea su parte entre la hierba de la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 16, NULL, 'Su corazón de hombre sea cambiado, y le sea dado corazón de bestia, y pasen sobre él siete tiempos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 17, NULL, 'La sentencia es por decreto de los vigilantes, y por dicho de los santos la resolución, para que conozcan los vivientes que el Altísimo gobierna el reino de los hombres, y que a quien él quiere lo da, y constituye sobre él al más bajo de los hombres.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 18, NULL, 'Yo el rey Nabucodonosor he visto este sueño. Tú, pues, Beltsasar, dirás la interpretación de él, porque todos los sabios de mi reino no han podido mostrarme su interpretación; mas tú puedes, porque mora en ti el espíritu de los dioses santos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 19, NULL, 'Entonces Daniel, cuyo nombre era Beltsasar, quedó atónito casi una hora, y sus pensamientos lo turbaban. El rey habló y dijo: Beltsasar, no te turben ni el sueño ni su interpretación. Beltsasar respondió y dijo: Señor mío, el sueño sea para tus enemigos, y su interpretación para los que mal te quieren.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 20, NULL, 'El árbol que viste, que crecía y se hacía fuerte, y cuya copa llegaba hasta el cielo, y que se veía desde todos los confines de la tierra,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 21, NULL, 'cuyo follaje era hermoso, y su fruto abundante, y en que había alimento para todos, debajo del cual moraban las bestias del campo, y en cuyas ramas anidaban las aves del cielo,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 22, NULL, 'tú mismo eres, oh rey, que creciste y te hiciste fuerte, pues creció tu grandeza y ha llegado hasta el cielo, y tu dominio hasta los confines de la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 23, NULL, 'Y en cuanto a lo que vio el rey, un vigilante y santo que descendía del cielo y decía: Cortad el árbol y destruidlo; mas la cepa de sus raíces dejaréis en la tierra, con atadura de hierro y de bronce en la hierba del campo; y sea mojado con el rocío del cielo, y con las bestias del campo sea su parte, hasta que pasen sobre él siete tiempos;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 24, NULL, 'esta es la interpretación, oh rey, y la sentencia del Altísimo, que ha venido sobre mi señor el rey:', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 25, NULL, 'Que te echarán de entre los hombres, y con las bestias del campo será tu morada, y con hierba del campo te apacentarán como a los bueyes, y con el rocío del cielo serás bañado; y siete tiempos pasarán sobre ti, hasta que conozcas que el Altísimo tiene dominio en el reino de los hombres, y que lo da a quien él quiere.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 26, NULL, 'Y en cuanto a la orden de dejar en la tierra la cepa de las raíces del mismo árbol, significa que tu reino te quedará firme, luego que reconozcas que el cielo gobierna.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 27, NULL, 'Por tanto, oh rey, acepta mi consejo: tus pecados redime con justicia, y tus iniquidades haciendo misericordias para con los oprimidos, pues tal vez será eso una prolongación de tu tranquilidad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 28, NULL, 'Todo esto vino sobre el rey Nabucodonosor.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 29, NULL, 'Al cabo de doce meses, paseando en el palacio real de Babilonia,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 30, NULL, 'habló el rey y dijo: ¿No es esta la gran Babilonia que yo edifiqué para casa real con la fuerza de mi poder, y para gloria de mi majestad?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 31, NULL, 'Aún estaba la palabra en la boca del rey, cuando vino una voz del cielo: A ti se te dice, rey Nabucodonosor: El reino ha sido quitado de ti;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 32, NULL, 'y de entre los hombres te arrojarán, y con las bestias del campo será tu habitación, y como a los bueyes te apacentarán; y siete tiempos pasarán sobre ti, hasta que reconozcas que el Altísimo tiene el dominio en el reino de los hombres, y lo da a quien él quiere.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 33, NULL, 'En la misma hora se cumplió la palabra sobre Nabucodonosor, y fue echado de entre los hombres; y comía hierba como los bueyes, y su cuerpo se mojaba con el rocío del cielo, hasta que su pelo creció como plumas de águila, y sus uñas como las de las aves.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 34, NULL, 'Mas al fin del tiempo yo Nabucodonosor alcé mis ojos al cielo, y mi razón me fue devuelta; y bendije al Altísimo, y alabé y glorifiqué al que vive para siempre, cuyo dominio es sempiterno, y su reino por todas las edades.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 35, NULL, 'Todos los habitantes de la tierra son considerados como nada; y él hace según su voluntad en el ejército del cielo, y en los habitantes de la tierra, y no hay quien detenga su mano, y le diga: ¿Qué haces?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 36, NULL, 'En el mismo tiempo mi razón me fue devuelta, y la majestad de mi reino, mi dignidad y mi grandeza volvieron a mí, y mis gobernadores y mis consejeros me buscaron; y fui restablecido en mi reino, y mayor grandeza me fue añadida.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 4, 37, NULL, 'Ahora yo Nabucodonosor alabo, engrandezco y glorifico al Rey del cielo, porque todas sus obras son verdaderas, y sus caminos justos; y él puede humillar a los que andan con soberbia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 1, 'La escritura en la pared', 'El rey Belsasar hizo un gran banquete a mil de sus príncipes, y en presencia de los mil bebía vino.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 2, NULL, 'Belsasar, con el gusto del vino, mandó que trajesen los vasos de oro y de plata que Nabucodonosor su padre había traído del templo de Jerusalén, para que bebiesen en ellos el rey y sus grandes, sus mujeres y sus concubinas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 3, NULL, 'Entonces fueron traídos los vasos de oro que habían traído del templo de la casa de Dios que estaba en Jerusalén, y bebieron en ellos el rey y sus príncipes, sus mujeres y sus concubinas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 4, NULL, 'Bebieron vino, y alabaron a los dioses de oro y de plata, de bronce, de hierro, de madera y de piedra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 5, NULL, 'En aquella misma hora aparecieron los dedos de una mano de hombre, que escribía delante del candelero sobre lo encalado de la pared del palacio real, y el rey veía la mano que escribía.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 6, NULL, 'Entonces el rey palideció, y sus pensamientos lo turbaron, y se debilitaron sus lomos, y sus rodillas daban la una contra la otra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 7, NULL, 'El rey gritó en alta voz que hiciesen venir magos, caldeos y adivinos; y dijo el rey a los sabios de Babilonia: Cualquiera que lea esta escritura y me muestre su interpretación, será vestido de púrpura, y un collar de oro llevará en su cuello, y será el tercer señor en el reino.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 8, NULL, 'Entonces fueron introducidos todos los sabios del rey, pero no pudieron leer la escritura ni mostrar al rey su interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 9, NULL, 'Entonces el rey Belsasar se turbó sobremanera, y palideció, y sus príncipes estaban perplejos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 10, NULL, 'La reina, por las palabras del rey y de sus príncipes, entró a la sala del banquete, y dijo: Rey, vive para siempre; no te turben tus pensamientos, ni palidezca tu rostro.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 11, NULL, 'En tu reino hay un hombre en el cual mora el espíritu de los dioses santos, y en los días de tu padre se halló en él luz e inteligencia y sabiduría, como sabiduría de los dioses; al que el rey Nabucodonosor tu padre, oh rey, constituyó jefe sobre todos los magos, astrólogos, caldeos y adivinos,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 12, NULL, 'por cuanto fue hallado en él mayor espíritu y ciencia y entendimiento, para interpretar sueños y descifrar enigmas y resolver dudas; esto es, en Daniel, al cual el rey puso por nombre Beltsasar. Llámese, pues, ahora a Daniel, y él te dará la interpretación.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 13, NULL, 'Entonces Daniel fue traído delante del rey. Y dijo el rey a Daniel: ¿Eres tú aquel Daniel de los hijos de la cautividad de Judá, que mi padre trajo de Judea?', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 14, NULL, 'Yo he oído de ti que el espíritu de los dioses santos está en ti, y que en ti se halló luz, entendimiento y mayor sabiduría.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 15, NULL, 'Y ahora fueron traídos delante de mí sabios y astrólogos para que leyesen esta escritura y me diesen su interpretación; pero no han podido mostrarme la interpretación del asunto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 16, NULL, 'Yo, pues, he oído de ti que puedes dar interpretaciones y resolver dificultades. Si ahora puedes leer esta escritura y darme su interpretación, serás vestido de púrpura, y un collar de oro llevarás en tu cuello, y serás el tercer señor en el reino.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 17, NULL, 'Entonces Daniel respondió y dijo delante del rey: Tus dones sean para ti, y da tus recompensas a otros. Leeré la escritura al rey, y le daré la interpretación.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 18, NULL, 'El Altísimo Dios, oh rey, dio a Nabucodonosor tu padre el reino y la grandeza, la gloria y la majestad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 19, NULL, 'Y por la grandeza que le dio, todos los pueblos, naciones y lenguas temblaban y temían delante de él. A quien quería mataba, y a quien quería daba vida; engrandecía a quien quería, y a quien quería humillaba.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 20, NULL, 'Mas cuando su corazón se ensoberbeció, y su espíritu se endureció en su orgullo, fue depuesto del trono de su reino, y despojado de su gloria.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 21, NULL, 'Y fue echado de entre los hijos de los hombres, y su mente se hizo semejante a la de las bestias, y con los asnos monteses fue su morada. Hierba le hicieron comer como a buey, y su cuerpo fue mojado con el rocío del cielo, hasta que reconoció que el Altísimo Dios tiene dominio sobre el reino de los hombres, y que pone sobre él al que le place.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 22, NULL, 'Y tú, su hijo Belsasar, no has humillado tu corazón, sabiendo todo esto;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 23, NULL, 'sino que contra el Señor del cielo te has ensoberbecido, e hiciste traer delante de ti los vasos de su casa, y tú y tus grandes, tus mujeres y tus concubinas, bebisteis vino en ellos; además de esto, diste alabanza a dioses de plata y oro, de bronce, de hierro, de madera y de piedra, que ni ven, ni oyen, ni saben; y al Dios en cuya mano está tu vida, y cuyos son todos tus caminos, nunca honraste.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 24, NULL, 'Entonces de su presencia fue enviada la mano que trazó esta escritura.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 25, NULL, 'Y la escritura que trazó es: MENE, MENE, TEKEL, UPARSIN.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 26, NULL, 'Esta es la interpretación del asunto: MENE: Contó Dios tu reino, y le ha puesto fin.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 27, NULL, 'TEKEL: Pesado has sido en balanza, y fuiste hallado falto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 28, NULL, 'PERES: Tu reino ha sido roto, y dado a los medos y a los persas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 29, NULL, 'Entonces mandó Belsasar vestir a Daniel de púrpura, y poner en su cuello un collar de oro, y proclamar que él era el tercer señor del reino.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 30, NULL, 'La misma noche fue muerto Belsasar rey de los caldeos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 5, 31, NULL, 'Y Darío de Media tomó el reino, siendo de sesenta y dos años.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 1, 'Daniel en el foso de los leones', 'Pareció bien a Darío constituir sobre el reino ciento veinte sátrapas, que gobernasen en todo el reino.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 2, NULL, 'Y sobre ellos tres gobernadores, de los cuales Daniel era uno, a quienes estos sátrapas diesen cuenta, para que el rey no fuese perjudicado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 3, NULL, 'Pero Daniel mismo era superior a estos sátrapas y gobernadores, porque había en él un espíritu superior; y el rey pensó en ponerlo sobre todo el reino.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 4, NULL, 'Entonces los gobernadores y sátrapas buscaban ocasión para acusar a Daniel en lo relacionado al reino; mas no podían hallar ocasión alguna o falta, porque él era fiel, y ningún vicio ni falta fue hallado en él.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 5, NULL, 'Entonces dijeron aquellos hombres: No hallaremos contra este Daniel ocasión alguna para acusarle, si no la hallamos contra él en relación con la ley de su Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 6, NULL, 'Entonces estos gobernadores y sátrapas se juntaron delante del rey, y le dijeron así: ¡Rey Darío, para siempre vive!', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 7, NULL, 'Todos los gobernadores del reino, magistrados, sátrapas, príncipes y capitanes han acordado por consejo que promulgues un edicto real y lo confirmes, que cualquiera que en el espacio de treinta días demande petición de cualquier dios u hombre fuera de ti, oh rey, sea echado en el foso de los leones.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 8, NULL, 'Ahora, oh rey, confirma el edicto y fírmalo, para que no pueda ser revocado, conforme a la ley de Media y de Persia, la cual no puede ser abrogada.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 9, NULL, 'Firmó, pues, el rey Darío el edicto y la prohibición.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 10, NULL, 'Cuando Daniel supo que el edicto había sido firmado, entró en su casa, y abiertas las ventanas de su cámara que daban hacia Jerusalén, se arrodillaba tres veces al día, y oraba y daba gracias delante de su Dios, como lo solía hacer antes.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 11, NULL, 'Entonces se juntaron aquellos hombres, y hallaron a Daniel orando y rogando en presencia de su Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 12, NULL, 'Fueron luego ante el rey y le hablaron del edicto real: ¿No has confirmado edicto que cualquiera que en el espacio de treinta días pida a cualquier dios u hombre fuera de ti, oh rey, sea echado en el foso de los leones? Respondió el rey diciendo: Verdad es, conforme a la ley de Media y de Persia, la cual no puede ser abrogada.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 13, NULL, 'Entonces respondieron y dijeron delante del rey: Daniel, que es de los hijos de los cautivos de Judá, no te respeta a ti, oh rey, ni acata el edicto que confirmaste, sino que tres veces al día hace su petición.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 14, NULL, 'Cuando el rey oyó el asunto, le pesó en gran manera, y resolvió librar a Daniel; y hasta la puesta del sol trabajó para librarle.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 15, NULL, 'Pero aquellos hombres rodearon al rey y le dijeron: Sepas, oh rey, que es ley de Media y de Persia que ningún edicto u ordenanza que el rey confirme puede ser abrogado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 16, NULL, 'Entonces el rey mandó, y trajeron a Daniel, y le echaron en el foso de los leones. Y el rey dijo a Daniel: El Dios tuyo, a quien tú continuamente sirves, él te libre.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 17, NULL, 'Y fue traída una piedra y puesta sobre la puerta del foso, la cual selló el rey con su anillo y con el anillo de sus príncipes, para que el acuerdo acerca de Daniel no se alterase.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 18, NULL, 'Luego el rey se fue a su palacio, y se acostó ayuno; ni instrumentos de música fueron traídos delante de él, y se le fue el sueño.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 19, NULL, 'El rey, pues, se levantó muy de mañana, y fue apresuradamente al foso de los leones.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 20, NULL, 'Y acercándose al foso llamó a voces a Daniel con voz triste, y le dijo: Daniel, siervo del Dios viviente, el Dios tuyo, a quien tú continuamente sirves, ¿te ha podido librar de los leones?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 21, NULL, 'Entonces Daniel respondió al rey: Oh rey, vive para siempre.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 22, NULL, 'Mi Dios envió su ángel, el cual cerró la boca de los leones, para que no me hiciesen daño, porque ante él fui hallado inocente; y aun delante de ti, oh rey, yo no he hecho nada malo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 23, NULL, 'Entonces se alegró el rey en gran manera a causa de él, y mandó sacar a Daniel del foso; y fue Daniel sacado del foso, y ninguna lesión se halló en él, porque había confiado en su Dios.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 24, NULL, 'Y dio orden el rey, y fueron traídos aquellos hombres que habían acusado a Daniel, y fueron echados en el foso de los leones ellos, sus hijos y sus mujeres; y aún no habían llegado al fondo del foso, cuando los leones se apoderaron de ellos y quebraron todos sus huesos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 25, NULL, 'Entonces el rey Darío escribió a todos los pueblos, naciones y lenguas que habitan en toda la tierra: Paz os sea multiplicada.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 26, NULL, 'De parte mía es puesta esta ordenanza: Que en todo el dominio de mi reino todos teman y tiemblen ante la presencia del Dios de Daniel; porque él es el Dios viviente y permanece por todos los siglos, y su reino no será jamás destruido, y su dominio perdurará hasta el fin.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 27, NULL, 'Él salva y libra, y hace señales y maravillas en el cielo y en la tierra; él ha librado a Daniel del poder de los leones.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 6, 28, NULL, 'Y este Daniel prosperó durante el reinado de Darío y durante el reinado de Ciro el persa.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 1, 'Visión de las cuatro bestias', 'En el primer año de Belsasar rey de Babilonia tuvo Daniel un sueño, y visiones de su cabeza mientras estaba en su lecho; luego escribió el sueño, y relató lo principal del asunto.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 2, NULL, 'Daniel dijo: Miraba yo en mi visión de noche, y he aquí que los cuatro vientos del cielo combatían en el gran mar.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 3, NULL, 'Y cuatro bestias grandes, diferentes la una de la otra, subían del mar.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 4, NULL, 'La primera era como león, y tenía alas de águila. Yo estaba mirando hasta que sus alas fueron arrancadas, y fue levantada del suelo y se puso enhiesta sobre los pies a manera de hombre, y le fue dado corazón de hombre.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 5, NULL, 'Y he aquí otra segunda bestia, semejante a un oso, la cual se alzaba de un costado más que del otro, y tenía en su boca tres costillas entre los dientes; y le fue dicho así: Levántate, devora mucha carne.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 6, NULL, 'Después de esto miré, y he aquí otra, semejante a un leopardo, con cuatro alas de ave en sus espaldas; tenía también esta bestia cuatro cabezas; y le fue dado dominio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 7, NULL, 'Después de esto miraba yo en las visiones de la noche, y he aquí la cuarta bestia, espantosa y terrible y en gran manera fuerte, la cual tenía unos dientes grandes de hierro; devoraba y desmenuzaba, y las sobras hollaba con sus pies, y era muy diferente de todas las bestias que vi antes de ella, y tenía diez cuernos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 8, NULL, 'Mientras yo contemplaba los cuernos, he aquí que otro cuerno pequeño salía entre ellos, y delante de él fueron arrancados tres cuernos de los primeros; y he aquí que este cuerno tenía ojos como de hombre, y una boca que hablaba grandes cosas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 9, NULL, 'Estuve mirando hasta que fueron puestos tronos, y se sentó un Anciano de días, cuyo vestido era blanco como la nieve, y el pelo de su cabeza como lana limpia; su trono llama de fuego, y las ruedas del mismo, fuego ardiente.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 10, NULL, 'Un río de fuego procedía y salía de delante de él; millares de millares le servían, y millones de millones asistían delante de él; el Juez se sentó, y los libros fueron abiertos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 11, NULL, 'Yo entonces miraba a causa del sonido de las grandes palabras que hablaba el cuerno; miraba hasta que mataron a la bestia, y su cuerpo fue destrozado y entregado para ser quemado en el fuego.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 12, NULL, 'Habían también quitado a las otras bestias su dominio, pero les había sido prolongada la vida hasta cierto tiempo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 13, NULL, 'Miraba yo en la visión de la noche, y he aquí con las nubes del cielo venía uno como un hijo de hombre, que vino hasta el Anciano de días, y le hicieron acercarse delante de él.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 14, NULL, 'Y le fue dado dominio, gloria y reino, para que todos los pueblos, naciones y lenguas le sirvieran; su dominio es dominio eterno, que nunca pasará, y su reino uno que no será destruido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 15, NULL, 'Se me turbó el espíritu a mí, Daniel, en medio de mi cuerpo, y las visiones de mi cabeza me asombraron.', 1, 'spa', 'RVR1960', NULL);\n"
;

  public static final String SQL_PARTE_2 = 
    "INSERT INTO Versiculo (\n" +
    "    codLengua_vscl, codVersion_vscl, codLibro_vscl, codCapitulo_vscl, codVersiculo_vscl, encabezado_vscl,\n" +
    "    contenido_vscl,\n" +
    "    parrafo_vscl, codLengua_vscl_ltr, codVersion_vscl_ltr, codLectura_vscl_ltr)\n" +
    "VALUES\n" +
    "('spa', 'RVR1960', 'Dn', 7, 16, NULL, 'Me acerqué a uno de los que asistían, y le pregunté la verdad acerca de todo esto. Y me habló, y me hizo conocer la interpretación de las cosas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 17, NULL, 'Estas cuatro grandes bestias son cuatro reyes que se levantarán en la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 18, NULL, 'Después recibirán el reino los santos del Altísimo, y poseerán el reino hasta el siglo, eternamente y para siempre.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 19, NULL, 'Entonces tuve deseo de saber la verdad acerca de la cuarta bestia, que era tan diferente de todas las otras, espantosa en gran manera, que tenía dientes de hierro y uñas de bronce, que devoraba y desmenuzaba, y las sobras hollaba con sus pies;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 20, NULL, 'asimismo acerca de los diez cuernos que tenía en su cabeza, y del otro que le había salido, delante del cual habían caído tres; y este mismo cuerno tenía ojos, y boca que hablaba grandes cosas, y parecía más grande que sus compañeros.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 21, NULL, 'Y veía yo que este cuerno hacía guerra contra los santos, y los vencía,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 22, NULL, 'hasta que vino el Anciano de días, y se dio el juicio a los santos del Altísimo; y llegó el tiempo, y los santos recibieron el reino.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 23, NULL, 'Dijo así: La cuarta bestia será un cuarto reino en la tierra, el cual será diferente de todos los otros reinos, y a toda la tierra devorará, trillará y despedazará.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 24, NULL, 'Y los diez cuernos significan que de aquel reino se levantarán diez reyes; y tras ellos se levantará otro, el cual será diferente de los primeros, y a tres reyes derribará.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 25, NULL, 'Y hablará palabras contra el Altísimo, y a los santos del Altísimo quebrantará, y pensará en cambiar los tiempos y la ley; y serán entregados en su mano hasta tiempo, y tiempos, y medio tiempo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 26, NULL, 'Pero se sentará el Juez, y le quitarán su dominio para que sea destruido y arruinado hasta el fin,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 27, NULL, 'y que el reino, y el dominio y la majestad de los reinos debajo de todo el cielo, sea dado al pueblo de los santos del Altísimo, cuyo reino es reino eterno, y todos los dominios le servirán y obedecerán.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 7, 28, NULL, 'Aquí fue el fin de sus palabras. En cuanto a mí, Daniel, mis pensamientos me turbaron y mi rostro se demudó; pero guardé el asunto en mi corazón.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 1, 'Visión del carnero y del macho cabrío', 'En el año tercero del reinado del rey Belsasar me apareció una visión a mí, Daniel, después de aquella que me había aparecido antes.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 2, NULL, 'Vi en visión; y cuando la vi, yo estaba en Susa, que es la capital del reino en la provincia de Elam; vi, pues, en visión, estando junto al río Ulai.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 3, NULL, 'Alcé los ojos y miré, y he aquí un carnero que estaba delante del río, y tenía dos cuernos; y aunque los cuernos eran altos, uno era más alto que el otro; y el más alto creció después.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 4, NULL, 'Vi que el carnero hería con los cuernos al poniente, al norte y al sur, y que ninguna bestia podía parar delante de él, ni había quien escapase de su poder; y hacía conforme a su voluntad, y se engrandecía.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 5, NULL, 'Mientras yo consideraba esto, he aquí un macho cabrío venía del lado del poniente sobre la faz de toda la tierra, sin tocar tierra; y aquel macho cabrío tenía un cuerno notable entre sus ojos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 6, NULL, 'Y vino hasta el carnero de dos cuernos, que yo había visto en la ribera del río, y corrió contra él con la furia de su fuerza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 7, NULL, 'Y lo vi que llegó junto al carnero, y se levantó contra él y lo hirió, y le quebró sus dos cuernos, y el carnero no tenía fuerzas para pararse delante de él; lo derribó, por tanto, en tierra, y lo pisoteó, y no hubo quien librase al carnero de su poder.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 8, NULL, 'Y el macho cabrío se engrandeció sobremanera; pero estando en su mayor fuerza, aquel gran cuerno fue quebrado, y en su lugar salieron otros cuatro cuernos notables hacia los cuatro vientos del cielo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 9, NULL, 'Y de uno de ellos salió un cuerno pequeño, que creció mucho al sur, y al oriente, y hacia la tierra gloriosa.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 10, NULL, 'Y se engrandeció hasta el ejército del cielo; y parte del ejército y de las estrellas echó por tierra, y las pisoteó.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 11, NULL, 'Aun se engrandeció contra el príncipe de los ejércitos, y por él fue quitado el continuo sacrificio, y el lugar de su santuario fue echado por tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 12, NULL, 'Y a causa de la prevaricación le fue entregado el ejército junto con el continuo sacrificio; y echó por tierra la verdad, e hizo cuanto quiso, y prosperó.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 13, NULL, 'Entonces oí a un santo que hablaba; y otro de los santos preguntó a aquel que hablaba: ¿Hasta cuándo durará la visión del continuo sacrificio, y la prevaricación asoladora entregando el santuario y el ejército para ser pisoteados?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 14, NULL, 'Y él dijo: Hasta dos mil trescientas tardes y mañanas; luego el santuario será purificado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 15, NULL, 'Y aconteció que mientras yo Daniel consideraba la visión y procuraba comprenderla, he aquí se puso delante de mí uno con apariencia de hombre.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 16, NULL, 'Y oí una voz de hombre entre las riberas del Ulai, que gritó y dijo: Gabriel, enseña a este la visión.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 17, NULL, 'Vino luego cerca de donde yo estaba; y con su venida me asombré, y me postré sobre mi rostro. Pero él me dijo: Entiende, hijo de hombre, porque la visión es para el tiempo del fin.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 18, NULL, 'Mientras él hablaba conmigo, caí dormido en tierra sobre mi rostro; y él me tocó, y me hizo estar en pie.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 19, NULL, 'Y dijo: He aquí yo te enseñaré lo que ha de venir al fin de la ira; porque eso es para el tiempo del fin.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 20, NULL, 'En cuanto al carnero que viste, que tenía dos cuernos, estos son los reyes de Media y de Persia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 21, NULL, 'El macho cabrío es el rey de Grecia, y el cuerno grande que tenía entre sus ojos es el rey primero.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 22, NULL, 'Y en cuanto al cuerno que fue quebrado, y sucedieron cuatro en su lugar, significa que cuatro reinos se levantarán de esa nación, aunque no con la fuerza de él.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 23, NULL, 'Y al fin del reinado de estos, cuando los transgresores lleguen al colmo, se levantará un rey altivo de rostro y entendido en enigmas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 24, NULL, 'Y su poder se fortalecerá, mas no con fuerza propia; y causará grandes ruinas, y prosperará, y hará arbitrariamente, y destruirá a los fuertes y al pueblo de los santos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 25, NULL, 'Con su sagacidad hará prosperar el engaño en su mano; y en su corazón se engrandecerá, y sin aviso destruirá a muchos; y se levantará contra el Príncipe de los príncipes, pero será quebrantado, aunque no por mano humana.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 26, NULL, 'La visión de las tardes y mañanas que se ha referido es verdadera; y tú guarda la visión, porque es para muchos días.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 8, 27, NULL, 'Y yo Daniel quedé quebrantado, y estuve enfermo algunos días, y cuando convalecí, atendí los negocios del rey; pero estaba espantado a causa de la visión, y no la entendía.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 1, 'Oración de Daniel por su pueblo', 'En el año primero de Darío hijo de Asuero, de la nación de los medos, que vino a ser rey sobre el reino de los caldeos,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 2, NULL, 'en el año primero de su reinado, yo Daniel miré atentamente en los libros el número de los años de que habló Jehová al profeta Jeremías, que habían de cumplirse las desolaciones de Jerusalén en setenta años.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 3, NULL, 'Y volví mi rostro a Dios el Señor, buscándole en oración y ruego, en ayuno, cilicio y ceniza.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 4, NULL, 'Y oré a Jehová mi Dios e hice confesión diciendo: Ahora, Señor, Dios grande, digno de ser temido, que guardas el pacto y la misericordia con los que te aman y guardan tus mandamientos;', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 5, NULL, 'hemos pecado, hemos cometido iniquidad, hemos hecho impíamente, y hemos sido rebeldes, y nos hemos apartado de tus mandamientos y de tus ordenanzas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 6, NULL, 'No hemos obedecido a tus siervos los profetas, que en tu nombre hablaron a nuestros reyes, a nuestros príncipes, a nuestros padres y a todo el pueblo de la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 7, NULL, 'Tuya es, Señor, la justicia, y nuestra la confusión de rostro, como en el día de hoy lleva todo hombre de Judá, los moradores de Jerusalén, y todo Israel, los de cerca y los de lejos, en todas las tierras adonde los has echado a causa de su rebelión con que se rebelaron contra ti.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 8, NULL, 'Oh Jehová, nuestra es la confusión de rostro, de nuestros reyes, de nuestros príncipes y de nuestros padres; porque contra ti pecamos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 9, NULL, 'De Jehová nuestro Dios es el tener misericordia y el perdonar, aunque contra él nos hemos rebelado,', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 10, NULL, 'y no obedecimos a la voz de Jehová nuestro Dios, para andar en sus leyes que él puso delante de nosotros por medio de sus siervos los profetas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 11, NULL, 'Todo Israel traspasó tu ley apartándose para no obedecer tu voz; por lo cual ha caído sobre nosotros la maldición y el juramento que está escrito en la ley de Moisés, siervo de Dios; porque contra él pecamos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 12, NULL, 'Y él ha cumplido la palabra que habló contra nosotros y contra nuestros jefes que nos gobernaron, trayendo sobre nosotros tan grande mal; pues nunca fue hecho debajo del cielo nada semejante a lo que se ha hecho contra Jerusalén.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 13, NULL, 'Conforme está escrito en la ley de Moisés, todo este mal vino sobre nosotros; y no hemos implorado el favor de Jehová nuestro Dios, para convertirnos de nuestras maldades y entender tu verdad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 14, NULL, 'Por tanto, Jehová veló sobre el mal y lo trajo sobre nosotros; porque justo es Jehová nuestro Dios en todas sus obras que ha hecho, porque no obedecimos a su voz.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 15, NULL, 'Ahora pues, Señor Dios nuestro, que sacaste tu pueblo de la tierra de Egipto con mano poderosa, y te hiciste renombre cual lo tienes hoy; hemos pecado, hemos hecho impíamente.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 16, NULL, 'Oh Señor, conforme a todos tus actos de justicia, apártese ahora tu ira y tu furor de sobre tu ciudad Jerusalén, tu santo monte; porque a causa de nuestros pecados, y por la maldad de nuestros padres, Jerusalén y tu pueblo son el oprobio de todos en derredor nuestro.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 17, NULL, 'Ahora pues, Dios nuestro, oye la oración de tu siervo, y sus ruegos; y haz que tu rostro resplandezca sobre tu santuario asolado, por amor del Señor.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 18, NULL, 'Inclina, oh Dios mío, tu oído, y oye; abre tus ojos, y mira nuestras desolaciones, y la ciudad sobre la cual es invocado tu nombre; porque no elevamos nuestros ruegos ante ti confiados en nuestras justicias, sino en tus muchas misericordias.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 19, NULL, 'Oye, Señor; oh Señor, perdona; presta oído, Señor, y hazlo; no tardes, por amor de ti mismo, Dios mío; porque tu nombre es invocado sobre tu ciudad y sobre tu pueblo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 20, 'Profecía de las setenta semanas', 'Aún estaba hablando y orando, y confesando mi pecado y el pecado de mi pueblo Israel, y derramaba mi ruego delante de Jehová mi Dios por el monte santo de mi Dios;', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 21, NULL, 'aún estaba hablando en oración, cuando el varón Gabriel, a quien había visto en la visión al principio, volando con presteza, vino a mí como a la hora del sacrificio de la tarde.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 22, NULL, 'Y me hizo entender, y habló conmigo, diciendo: Daniel, ahora he salido para darte sabiduría y entendimiento.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 23, NULL, 'Al principio de tus ruegos fue dada la orden, y yo he venido para enseñártela, porque tú eres muy amado. Entiende, pues, la orden, y entiende la visión.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 24, NULL, 'Setenta semanas están determinadas sobre tu pueblo y sobre tu santa ciudad, para terminar la prevaricación, y poner fin al pecado, y expiar la iniquidad, para traer la justicia perdurable, y sellar la visión y la profecía, y ungir al Santo de los santos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 25, NULL, 'Sabe, pues, y entiende, que desde la salida de la orden para restaurar y edificar a Jerusalén hasta el Mesías Príncipe, habrá siete semanas, y sesenta y dos semanas; se volverá a edificar la plaza y el muro en tiempos angustiosos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 26, NULL, 'Y después de las sesenta y dos semanas se quitará la vida al Mesías, mas no por sí; y el pueblo de un príncipe que ha de venir destruirá la ciudad y el santuario; y su fin será con inundación, y hasta el fin de la guerra durarán las devastaciones.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 9, 27, NULL, 'Y por otra semana confirmará el pacto con muchos; a la mitad de la semana hará cesar el sacrificio y la ofrenda. Después con la muchedumbre de las abominaciones vendrá el desolador, hasta que venga la consumación, y lo que está determinado se derrame sobre el desolador.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 1, 'Visión de Daniel junto al río', 'En el año tercero de Ciro rey de Persia fue revelada palabra a Daniel, llamado Beltsasar; y la palabra era verdadera, y el conflicto grande; pero él comprendió la palabra, y tuvo inteligencia en la visión.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 2, NULL, 'En aquellos días yo Daniel estuve afligido por espacio de tres semanas.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 3, NULL, 'No comí manjar delicado, ni entró en mi boca carne ni vino, ni me ungí con ungüento, hasta que se cumplieron las tres semanas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 4, NULL, 'Y el día veinticuatro del mes primero estaba yo a la orilla del gran río Hidekel.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 5, NULL, 'Y alcé mis ojos y miré, y he aquí un varón vestido de lino, y ceñidos sus lomos de oro de Ufaz.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 6, NULL, 'Su cuerpo era como de berilo, y su rostro parecía un relámpago, y sus ojos como antorchas de fuego, y sus brazos y sus pies como de color de bronce bruñido, y el sonido de sus palabras como el estruendo de una multitud.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 7, NULL, 'Y sólo yo, Daniel, vi aquella visión, y no la vieron los hombres que estaban conmigo, sino que se apoderó de ellos un gran temor, y huyeron y se escondieron.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 8, NULL, 'Quedé, pues, yo solo, y vi esta gran visión, y no quedó fuerza en mí, antes mi fuerza se cambió en desfallecimiento, y no tuve vigor alguno.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 9, NULL, 'Pero oí el sonido de sus palabras; y al oír el sonido de sus palabras, caí sobre mi rostro en un profundo sueño, con mi rostro en tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 10, NULL, 'Y he aquí una mano me tocó, e hizo que me pusiese sobre mis rodillas y sobre las palmas de mis manos.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 11, NULL, 'Y me dijo: Daniel, varón muy amado, está atento a las palabras que te hablaré, y ponte en pie; porque a ti he sido enviado ahora. Mientras hablaba esto conmigo, me puse en pie temblando.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 12, NULL, 'Entonces me dijo: Daniel, no temas; porque desde el primer día que dispusiste tu corazón a entender y a humillarte en la presencia de tu Dios, fueron oídas tus palabras; y a causa de tus palabras yo he venido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 13, NULL, 'Mas el príncipe del reino de Persia se me opuso durante veintiún días; pero he aquí Miguel, uno de los principales príncipes, vino para ayudarme, y quedé allí con los reyes de Persia.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 14, NULL, 'He venido para hacerte saber lo que ha de venir a tu pueblo en los postreros días; porque la visión es para esos días.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 15, NULL, 'Mientras me decía estas palabras, estaba yo con los ojos puestos en tierra, y enmudecido.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 16, NULL, 'Pero he aquí, uno con semejanza de hijo de hombre tocó mis labios. Entonces abrí mi boca y hablé, y dije al que estaba delante de mí: Señor mío, con la visión me han sobrevenido dolores, y no me queda fuerza.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 17, NULL, '¿Cómo, pues, podrá el siervo de mi señor hablar con mi señor? Porque al instante me faltó la fuerza, y no me quedó aliento.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 18, NULL, 'Y aquel que tenía semejanza de hombre me tocó otra vez, y me fortaleció,', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 19, NULL, 'y me dijo: Muy amado, no temas; la paz sea contigo; esfuérzate y aliéntate. Y mientras él me hablaba, recobré las fuerzas, y dije: Hable mi señor, porque me has fortalecido.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 20, NULL, 'Él me dijo: ¿Sabes por qué he venido a ti? Pues ahora tengo que volver para pelear contra el príncipe de Persia; y al terminar con él, el príncipe de Grecia vendrá.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 10, 21, NULL, 'Pero yo te declararé lo que está escrito en el libro de la verdad; y ninguno me ayuda contra ellos, sino Miguel vuestro príncipe.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 1, NULL, 'Y yo mismo, en el año primero de Darío el medo, estuve para animarlo y fortalecerlo.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 2, 'Los reyes del norte y del sur', 'Y ahora yo te mostraré la verdad. He aquí que aún habrá tres reyes en Persia, y el cuarto se hará de grandes riquezas más que todos ellos; y al hacerse fuerte con sus riquezas, levantará a todos contra el reino de Grecia.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 3, NULL, 'Se levantará luego un rey valiente, el cual dominará con gran poder y hará su voluntad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 4, NULL, 'Pero cuando se haya levantado, su reino será quebrantado y repartido hacia los cuatro vientos del cielo; no a sus descendientes, ni según el dominio con que él dominó; porque su reino será arrancado, y será para otros fuera de ellos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 5, NULL, 'Y se hará fuerte el rey del sur; mas uno de sus príncipes será más fuerte que él, y se hará poderoso; su dominio será grande.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 6, NULL, 'Al cabo de años harán alianza, y la hija del rey del sur vendrá al rey del norte para hacer la paz. Pero ella no podrá retener la fuerza de su brazo, ni permanecerá él, ni su brazo; porque será entregada ella y los que la habían traído, asimismo su hijo, y los que estaban de parte de ella en aquel tiempo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 7, NULL, 'Pero un renuevo de sus raíces se levantará sobre su trono, y vendrá con ejército contra el rey del norte, y entrará en la fortaleza, y hará en ellos a su arbitrio, y predominará.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 8, NULL, 'Y aun a los dioses de ellos, sus imágenes fundidas y sus objetos preciosos de plata y de oro, llevará cautivos a Egipto; y por años se mantendrá él contra el rey del norte.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 9, NULL, 'Así entrará en el reino el rey del sur, y volverá a su tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 10, NULL, 'Mas los hijos de aquel se airarán, y reunirán multitud de grandes ejércitos; y vendrá apresuradamente e inundará, y pasará adelante; luego volverá y llevará la guerra hasta su fortaleza.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 11, NULL, 'Por lo cual se enfurecerá el rey del sur, y saldrá y peleará contra el rey del norte; y pondrá en campaña multitud grande, y toda aquella multitud será entregada en su mano.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 12, NULL, 'Y al llevarse él la multitud, se elevará su corazón, y derribará a muchos millares; mas no prevalecerá.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 13, NULL, 'Y el rey del norte volverá a poner en campaña una multitud mayor que la primera, y al cabo de algunos años vendrá apresuradamente con gran ejército y con muchas riquezas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 14, NULL, 'En aquellos tiempos se levantarán muchos contra el rey del sur; y hombres turbulentos de tu pueblo se levantarán para cumplir la visión, pero ellos caerán.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 15, NULL, 'Vendrá, pues, el rey del norte, y levantará baluartes, y tomará la ciudad fuerte; y las fuerzas del sur no podrán sostenerse, ni sus tropas escogidas, porque no habrá fuerzas para resistir.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 16, NULL, 'Y el que vendrá contra él hará su voluntad, y no habrá quien se le pueda enfrentar; y estará en la tierra gloriosa, la cual será consumida en su poder.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 17, NULL, 'Afirmará luego su rostro para venir con el poder de todo su reino; y hará con aquel convenios, y le dará una hija de mujeres para destruirle; pero no permanecerá, ni tendrá éxito.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 18, NULL, 'Volverá después su rostro a las costas, y tomará muchas; mas un príncipe hará cesar su afrenta, y aun hará volver sobre él su oprobio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 19, NULL, 'Luego volverá su rostro a las fortalezas de su tierra; mas tropezará y caerá, y no será hallado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 20, NULL, 'Y se levantará en su lugar uno que hará pasar un cobrador de tributos por la gloria del reino; pero en pocos días será quebrantado, aunque no en ira, ni en batalla.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 21, NULL, 'Y le sucederá en su lugar un hombre despreciable, al cual no darán la honra del reino; pero vendrá sin aviso y tomará el reino con halagos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 22, NULL, 'Las fuerzas enemigas serán barridas delante de él como con inundación de aguas; serán del todo destruidos, junto con el príncipe del pacto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 23, NULL, 'Y después del pacto con él, engañará y subirá, y saldrá vencedor con poca gente.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 24, NULL, 'Estando la provincia en paz y en abundancia, entrará y hará lo que no hicieron sus padres, ni los padres de sus padres; botín, despojos y riquezas repartirá a sus soldados, y contra las fortalezas formará sus designios; y esto por un tiempo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 25, NULL, 'Y despertará sus fuerzas y su ardor contra el rey del sur con gran ejército; y el rey del sur se empeñará en la guerra con grande y muy fuerte ejército; mas no prevalecerá, porque le harán traición.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 26, NULL, 'Aun los que coman de sus manjares le quebrantarán; y su ejército será destruido, y caerán muchos muertos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 27, NULL, 'El corazón de estos dos reyes será para hacer mal, y en una misma mesa hablarán mentira; mas no servirá de nada, porque el plazo aún no habrá llegado.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 28, NULL, 'Y volverá a su tierra con gran riqueza, y su corazón será contra el pacto santo; hará su voluntad, y volverá a su tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 29, NULL, 'Al tiempo señalado volverá al sur; mas no será la postrera venida como la primera.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 30, NULL, 'Porque vendrán contra él naves de Quitim, y él se contristará, y volverá, y se enojará contra el pacto santo, y hará según su voluntad; volverá, pues, y se entenderá con los que abandonen el santo pacto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 31, NULL, 'Y se levantarán de su parte tropas que profanarán el santuario y la fortaleza, y quitarán el continuo sacrificio, y pondrán la abominación desoladora.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 32, NULL, 'Con lisonjas seducirá a los violadores del pacto; mas el pueblo que conoce a su Dios se esforzará y actuará.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 33, NULL, 'Y los sabios del pueblo instruirán a muchos; y por algunos días caerán a espada y a fuego, en cautividad y despojo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 34, NULL, 'Y en su caída serán ayudados de pequeño socorro; y muchos se juntarán a ellos con lisonjas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 35, NULL, 'También algunos de los sabios caerán para ser depurados y limpiados y emblanquecidos, hasta el tiempo determinado; porque aun para esto hay plazo.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 36, NULL, 'Y el rey hará su voluntad, y se ensoberbecerá, y se engrandecerá sobre todo dios; y contra el Dios de los dioses hablará maravillas, y prosperará, hasta que sea consumada la ira; porque lo determinado se cumplirá.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 37, NULL, 'Del Dios de sus padres no hará caso, ni del amor de las mujeres; ni respetará a dios alguno, porque sobre todo se engrandecerá.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 38, NULL, 'Mas honrará en su lugar al dios de las fortalezas, dios que sus padres no conocieron; lo honrará con oro y plata, con piedras preciosas y con cosas de gran precio.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 39, NULL, 'Con un dios ajeno se hará de las fortalezas más inexpugnables, y colmará de honores a los que le reconozcan, y por precio repartirá la tierra.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 40, NULL, 'Pero al cabo del tiempo el rey del sur contenderá con él; y el rey del norte se levantará contra él como una tempestad, con carros y gente de a caballo, y muchas naves; y entrará por las tierras, e inundará, y pasará.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 41, NULL, 'Entrará a la tierra gloriosa, y muchas provincias caerán; mas estas escaparán de su mano: Edom y Moab, y la mayoría de los hijos de Amón.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 42, NULL, 'Extenderá su mano contra las tierras, y no escapará el país de Egipto.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 43, NULL, 'Y se apoderará de los tesoros de oro y plata, y de todas las cosas preciosas de Egipto; y los de Libia y de Etiopía le seguirán.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 44, NULL, 'Pero noticias del oriente y del norte lo atemorizarán, y saldrá con gran ira para destruir y matar a muchos.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 11, 45, NULL, 'Y plantará las tiendas de su palacio entre los mares y el monte glorioso y santo; mas llegará a su fin, y no tendrá quien le ayude.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 1, 'El tiempo del fin', 'En aquel tiempo se levantará Miguel, el gran príncipe que está de parte de los hijos de tu pueblo; y será tiempo de angustia, cual nunca fue desde que hubo gente hasta entonces; pero en aquel tiempo será libertado tu pueblo, todos los que se hallen escritos en el libro.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 2, NULL, 'Y muchos de los que duermen en el polvo de la tierra serán despertados, unos para vida eterna, y otros para vergüenza y confusión perpetua.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 3, NULL, 'Los entendidos resplandecerán como el resplandor del firmamento; y los que enseñan la justicia a la multitud, como las estrellas a perpetua eternidad.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 4, NULL, 'Pero tú, Daniel, cierra las palabras y sella el libro hasta el tiempo del fin. Muchos correrán de aquí para allá, y la ciencia se aumentará.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 5, NULL, 'Y yo Daniel miré, y he aquí otros dos que estaban en pie, el uno a este lado del río, y el otro al otro lado del río.', 1, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 6, NULL, 'Y dijo uno al varón vestido de lino, que estaba sobre las aguas del río: ¿Cuándo será el fin de estas maravillas?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 7, NULL, 'Y oí al varón vestido de lino, que estaba sobre las aguas del río, el cual alzó su diestra y su siniestra al cielo, y juró por el que vive por los siglos, que será por tiempo, tiempos, y la mitad de un tiempo. Y cuando se acabe la dispersión del poder del pueblo santo, todas estas cosas serán cumplidas.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 8, NULL, 'Y yo oí, mas no entendí. Y dije: Señor mío, ¿cuál será el fin de estas cosas?', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 9, NULL, 'Él respondió: Anda, Daniel, pues estas palabras están cerradas y selladas hasta el tiempo del fin.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 10, NULL, 'Muchos serán limpios, y emblanquecidos y purificados; los impíos procederán impíamente, y ninguno de los impíos entenderá, pero los entendidos comprenderán.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 11, NULL, 'Y desde el tiempo que sea quitado el continuo sacrificio hasta la abominación desoladora, habrá mil doscientos noventa días.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 12, NULL, 'Bienaventurado el que espere, y llegue a mil trescientos treinta y cinco días.', 0, 'spa', 'RVR1960', NULL),\n" +
    "('spa', 'RVR1960', 'Dn', 12, 13, NULL, 'Y tú irás hasta el fin, y reposarás, y te levantarás para recibir tu heredad al fin de los días.', 0, 'spa', 'RVR1960', NULL);\n"
;

}